// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"baboflow/internal/biz"
	"baboflow/internal/biz/agentkit"
	"baboflow/internal/biz/rulegokit"
	"baboflow/internal/conf"
	"baboflow/internal/data"
	"baboflow/internal/server"
	"baboflow/internal/service"
)

// Injectors from wire.go:

// wireApp 由 wire 生成具体实现（见 wire_gen.go）。
func wireApp(c *conf.Config) (*App, func(), error) {
	db, err := data.NewDB(c)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(db)
	authUsecase := biz.NewAuthUsecase(authRepo)
	auditDataRepo := data.NewAuditRepo(db)
	auditUsecase := biz.NewAuditUsecase(auditDataRepo)
	authProtoService := service.NewAuthProtoService(authUsecase, auditUsecase)
	archeryRepo := data.NewArcheryRepo(db)
	archeryUsecase := biz.NewArcheryUsecase(archeryRepo, c)
	archeryProtoService := service.NewArcheryProtoService(archeryUsecase, auditUsecase)
	llmRepo := data.NewLLMRepo(db)
	llmUsecase := biz.NewLLMUsecase(llmRepo, c)
	llmProtoService := service.NewLLMProtoService(llmUsecase, auditUsecase)
	componentRepo := data.NewComponentRepo(db)
	componentSync := biz.NewComponentSync(componentRepo)
	componentProtoService := service.NewComponentProtoService(componentRepo, componentSync)
	ruleChainRepo := data.NewRuleChainRepo(db)
	manager := rulegokit.NewManager()
	ruleChainUsecase := biz.NewRuleChainUsecase(ruleChainRepo, manager)
	ruleChainProtoService := service.NewRuleChainProtoService(ruleChainUsecase, auditUsecase)
	agentDataRepo := data.NewAgentDataRepo(db)
	agentRepo := data.NewAgentRepo(db)
	skillRepo := data.NewAgentkitSkillRepo(db)
	llmResolver := data.NewAgentkitLLMResolver(db)
	modelFactory := agentkit.NewModelFactory(c)
	builtinTools := agentkit.ProvideBuiltinTools(c)
	agentkitManager := agentkit.NewManager(agentRepo, skillRepo, llmResolver, modelFactory, builtinTools)
	assetStore := data.NewAssetStore(c)
	tracer, cleanup, err := agentkit.ProvideTracer(c)
	if err != nil {
		return nil, nil, err
	}
	agentUsecase := biz.NewAgentUsecase(agentDataRepo, agentkitManager, c, assetStore, tracer)
	agentProtoService := service.NewAgentProtoService(agentUsecase)
	skillDataRepo := data.NewBizSkillDataRepo(db)
	skillUsecase := biz.NewSkillUsecase(skillDataRepo, ruleChainUsecase, c)
	skillProtoService := service.NewSkillProtoService(skillUsecase, auditUsecase)
	mcpDataRepo := data.NewMcpRepo(db)
	mcpUsecase := biz.NewMcpUsecase(mcpDataRepo, ruleChainUsecase)
	mcpClientBuilder := agentkit.NewMcpClientBuilder()
	mcpProtoService := service.NewMcpProtoService(mcpUsecase, mcpClientBuilder, auditUsecase)
	boardDataRepo := data.NewBoardRepo(db)
	boardUsecase := biz.NewBoardUsecase(boardDataRepo, ruleChainUsecase)
	boardProtoService := service.NewBoardProtoService(boardUsecase, auditUsecase)
	auditProtoService := service.NewAuditProtoService(auditUsecase)
	cronDataRepo := data.NewCronRepo(db)
	cronUsecase := biz.NewCronUsecase(cronDataRepo, ruleChainUsecase)
	cronProtoService := service.NewCronProtoService(cronUsecase)
	rateLimiters := service.NewRateLimiters()
	feishuUsecase := biz.NewFeishuUsecase(authRepo, c)
	feishuHandler := service.NewFeishuHandler(feishuUsecase)
	agentHandler := service.NewAgentHandler(agentUsecase)
	skillHandler := service.NewSkillHandler(skillUsecase)
	wsHub := service.NewWsHub(agentUsecase, authUsecase)
	httpServer := server.NewHTTPServer(c, authUsecase, authProtoService, archeryProtoService, llmProtoService, componentProtoService, ruleChainProtoService, agentProtoService, skillProtoService, mcpProtoService, boardProtoService, auditProtoService, cronProtoService, rateLimiters, feishuHandler, agentHandler, skillHandler, wsHub, mcpUsecase, db)
	grpcServer := server.NewGRPCServer(c, authUsecase, authProtoService, archeryProtoService, llmProtoService, componentProtoService, ruleChainProtoService, agentProtoService, skillProtoService, mcpProtoService, boardProtoService, auditProtoService, cronProtoService, rateLimiters)
	platformDeps := biz.NewPlatformDeps(componentRepo, ruleChainUsecase, skillUsecase)
	platformTools := biz.NewPlatformTools(platformDeps)
	app := newApp(httpServer, grpcServer, c, db, ruleChainUsecase, mcpUsecase, cronUsecase, boardUsecase, skillUsecase, archeryUsecase, auditUsecase, agentUsecase, agentkitManager, manager, componentSync, componentRepo, platformTools, tracer, rateLimiters, feishuHandler, skillHandler)
	return app, func() {
		cleanup()
	}, nil
}
