// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_List_FullMethodName          = "/baboflow.v1.AgentService/List"
	AgentService_Create_FullMethodName        = "/baboflow.v1.AgentService/Create"
	AgentService_Get_FullMethodName           = "/baboflow.v1.AgentService/Get"
	AgentService_Update_FullMethodName        = "/baboflow.v1.AgentService/Update"
	AgentService_Delete_FullMethodName        = "/baboflow.v1.AgentService/Delete"
	AgentService_ListSessions_FullMethodName  = "/baboflow.v1.AgentService/ListSessions"
	AgentService_CreateSession_FullMethodName = "/baboflow.v1.AgentService/CreateSession"
	AgentService_DeleteSession_FullMethodName = "/baboflow.v1.AgentService/DeleteSession"
	AgentService_ListMessages_FullMethodName  = "/baboflow.v1.AgentService/ListMessages"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Old: GET /api/v1/agents?keyword=.
	List(ctx context.Context, in *AgentListRequest, opts ...grpc.CallOption) (*AgentListResponse, error)
	// Old: POST /api/v1/agents.
	Create(ctx context.Context, in *AgentInput, opts ...grpc.CallOption) (*Agent, error)
	// Old: GET /api/v1/agents/{key}.
	Get(ctx context.Context, in *AgentKeyRequest, opts ...grpc.CallOption) (*Agent, error)
	// Old: PUT /api/v1/agents/{key}.
	Update(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*AgentOk, error)
	// Old: DELETE /api/v1/agents/{key}.
	Delete(ctx context.Context, in *AgentKeyRequest, opts ...grpc.CallOption) (*AgentOk, error)
	// Old: GET /api/v1/agents/{key}/sessions.
	ListSessions(ctx context.Context, in *AgentSessionListRequest, opts ...grpc.CallOption) (*AgentSessionList, error)
	// Old: POST /api/v1/agents/{key}/sessions.
	CreateSession(ctx context.Context, in *CreateAgentSessionRequest, opts ...grpc.CallOption) (*AgentSession, error)
	// Old: DELETE /api/v1/agents/sessions/{sessionId}.
	DeleteSession(ctx context.Context, in *AgentSessionRequest, opts ...grpc.CallOption) (*AgentOk, error)
	// Old: GET /api/v1/agents/sessions/{sessionId}/messages.
	ListMessages(ctx context.Context, in *AgentSessionRequest, opts ...grpc.CallOption) (*AgentMessageList, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) List(ctx context.Context, in *AgentListRequest, opts ...grpc.CallOption) (*AgentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentListResponse)
	err := c.cc.Invoke(ctx, AgentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Create(ctx context.Context, in *AgentInput, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Get(ctx context.Context, in *AgentKeyRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Update(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*AgentOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentOk)
	err := c.cc.Invoke(ctx, AgentService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Delete(ctx context.Context, in *AgentKeyRequest, opts ...grpc.CallOption) (*AgentOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentOk)
	err := c.cc.Invoke(ctx, AgentService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSessions(ctx context.Context, in *AgentSessionListRequest, opts ...grpc.CallOption) (*AgentSessionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSessionList)
	err := c.cc.Invoke(ctx, AgentService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateSession(ctx context.Context, in *CreateAgentSessionRequest, opts ...grpc.CallOption) (*AgentSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSession)
	err := c.cc.Invoke(ctx, AgentService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteSession(ctx context.Context, in *AgentSessionRequest, opts ...grpc.CallOption) (*AgentOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentOk)
	err := c.cc.Invoke(ctx, AgentService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListMessages(ctx context.Context, in *AgentSessionRequest, opts ...grpc.CallOption) (*AgentMessageList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentMessageList)
	err := c.cc.Invoke(ctx, AgentService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Old: GET /api/v1/agents?keyword=.
	List(context.Context, *AgentListRequest) (*AgentListResponse, error)
	// Old: POST /api/v1/agents.
	Create(context.Context, *AgentInput) (*Agent, error)
	// Old: GET /api/v1/agents/{key}.
	Get(context.Context, *AgentKeyRequest) (*Agent, error)
	// Old: PUT /api/v1/agents/{key}.
	Update(context.Context, *AgentUpdateRequest) (*AgentOk, error)
	// Old: DELETE /api/v1/agents/{key}.
	Delete(context.Context, *AgentKeyRequest) (*AgentOk, error)
	// Old: GET /api/v1/agents/{key}/sessions.
	ListSessions(context.Context, *AgentSessionListRequest) (*AgentSessionList, error)
	// Old: POST /api/v1/agents/{key}/sessions.
	CreateSession(context.Context, *CreateAgentSessionRequest) (*AgentSession, error)
	// Old: DELETE /api/v1/agents/sessions/{sessionId}.
	DeleteSession(context.Context, *AgentSessionRequest) (*AgentOk, error)
	// Old: GET /api/v1/agents/sessions/{sessionId}/messages.
	ListMessages(context.Context, *AgentSessionRequest) (*AgentMessageList, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) List(context.Context, *AgentListRequest) (*AgentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAgentServiceServer) Create(context.Context, *AgentInput) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAgentServiceServer) Get(context.Context, *AgentKeyRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAgentServiceServer) Update(context.Context, *AgentUpdateRequest) (*AgentOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAgentServiceServer) Delete(context.Context, *AgentKeyRequest) (*AgentOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAgentServiceServer) ListSessions(context.Context, *AgentSessionListRequest) (*AgentSessionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentServiceServer) CreateSession(context.Context, *CreateAgentSessionRequest) (*AgentSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentServiceServer) DeleteSession(context.Context, *AgentSessionRequest) (*AgentOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedAgentServiceServer) ListMessages(context.Context, *AgentSessionRequest) (*AgentMessageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).List(ctx, req.(*AgentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Create(ctx, req.(*AgentInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Get(ctx, req.(*AgentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Update(ctx, req.(*AgentUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Delete(ctx, req.(*AgentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSessions(ctx, req.(*AgentSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSession(ctx, req.(*CreateAgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteSession(ctx, req.(*AgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListMessages(ctx, req.(*AgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AgentService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AgentService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AgentService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AgentService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AgentService_Delete_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentService_ListSessions_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AgentService_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _AgentService_DeleteSession_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _AgentService_ListMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/agent.proto",
}
