// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/agent.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentServiceCreate = "/baboflow.v1.AgentService/Create"
const OperationAgentServiceCreateSession = "/baboflow.v1.AgentService/CreateSession"
const OperationAgentServiceDelete = "/baboflow.v1.AgentService/Delete"
const OperationAgentServiceDeleteSession = "/baboflow.v1.AgentService/DeleteSession"
const OperationAgentServiceGet = "/baboflow.v1.AgentService/Get"
const OperationAgentServiceList = "/baboflow.v1.AgentService/List"
const OperationAgentServiceListMessages = "/baboflow.v1.AgentService/ListMessages"
const OperationAgentServiceListSessions = "/baboflow.v1.AgentService/ListSessions"
const OperationAgentServiceUpdate = "/baboflow.v1.AgentService/Update"

type AgentServiceHTTPServer interface {
	// Create Old: POST /api/v1/agents.
	Create(context.Context, *AgentInput) (*Agent, error)
	// CreateSession Old: POST /api/v1/agents/{key}/sessions.
	CreateSession(context.Context, *CreateAgentSessionRequest) (*AgentSession, error)
	// Delete Old: DELETE /api/v1/agents/{key}.
	Delete(context.Context, *AgentKeyRequest) (*AgentOk, error)
	// DeleteSession Old: DELETE /api/v1/agents/sessions/{sessionId}.
	DeleteSession(context.Context, *AgentSessionRequest) (*AgentOk, error)
	// Get Old: GET /api/v1/agents/{key}.
	Get(context.Context, *AgentKeyRequest) (*Agent, error)
	// List Old: GET /api/v1/agents?keyword=.
	List(context.Context, *AgentListRequest) (*AgentListResponse, error)
	// ListMessages Old: GET /api/v1/agents/sessions/{sessionId}/messages.
	ListMessages(context.Context, *AgentSessionRequest) (*AgentMessageList, error)
	// ListSessions Old: GET /api/v1/agents/{key}/sessions.
	ListSessions(context.Context, *AgentSessionListRequest) (*AgentSessionList, error)
	// Update Old: PUT /api/v1/agents/{key}.
	Update(context.Context, *AgentUpdateRequest) (*AgentOk, error)
}

func RegisterAgentServiceHTTPServer(s *http.Server, srv AgentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/agents", _AgentService_List6_HTTP_Handler(srv))
	r.POST("/api/v1/agents", _AgentService_Create3_HTTP_Handler(srv))
	r.GET("/api/v1/agents/{key}", _AgentService_Get3_HTTP_Handler(srv))
	r.PUT("/api/v1/agents/{key}", _AgentService_Update3_HTTP_Handler(srv))
	r.DELETE("/api/v1/agents/{key}", _AgentService_Delete4_HTTP_Handler(srv))
	r.GET("/api/v1/agent-sessions", _AgentService_ListSessions0_HTTP_Handler(srv))
	r.POST("/api/v1/agent-sessions", _AgentService_CreateSession0_HTTP_Handler(srv))
	r.DELETE("/api/v1/agent-sessions/{sessionId}", _AgentService_DeleteSession0_HTTP_Handler(srv))
	r.GET("/api/v1/agent-sessions/{sessionId}/messages", _AgentService_ListMessages0_HTTP_Handler(srv))
}

func _AgentService_List6_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*AgentListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentListResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentService_Create3_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*AgentInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Agent)
		return ctx.Result(200, reply)
	}
}

func _AgentService_Get3_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*AgentKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Agent)
		return ctx.Result(200, reply)
	}
}

func _AgentService_Update3_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*AgentUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentOk)
		return ctx.Result(200, reply)
	}
}

func _AgentService_Delete4_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*AgentKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentOk)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListSessions0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentSessionListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*AgentSessionListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentSessionList)
		return ctx.Result(200, reply)
	}
}

func _AgentService_CreateSession0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAgentSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateAgentSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentSession)
		return ctx.Result(200, reply)
	}
}

func _AgentService_DeleteSession0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceDeleteSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSession(ctx, req.(*AgentSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentOk)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ListMessages0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AgentSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*AgentSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AgentMessageList)
		return ctx.Result(200, reply)
	}
}

type AgentServiceHTTPClient interface {
	// Create Old: POST /api/v1/agents.
	Create(ctx context.Context, req *AgentInput, opts ...http.CallOption) (rsp *Agent, err error)
	// CreateSession Old: POST /api/v1/agents/{key}/sessions.
	CreateSession(ctx context.Context, req *CreateAgentSessionRequest, opts ...http.CallOption) (rsp *AgentSession, err error)
	// Delete Old: DELETE /api/v1/agents/{key}.
	Delete(ctx context.Context, req *AgentKeyRequest, opts ...http.CallOption) (rsp *AgentOk, err error)
	// DeleteSession Old: DELETE /api/v1/agents/sessions/{sessionId}.
	DeleteSession(ctx context.Context, req *AgentSessionRequest, opts ...http.CallOption) (rsp *AgentOk, err error)
	// Get Old: GET /api/v1/agents/{key}.
	Get(ctx context.Context, req *AgentKeyRequest, opts ...http.CallOption) (rsp *Agent, err error)
	// List Old: GET /api/v1/agents?keyword=.
	List(ctx context.Context, req *AgentListRequest, opts ...http.CallOption) (rsp *AgentListResponse, err error)
	// ListMessages Old: GET /api/v1/agents/sessions/{sessionId}/messages.
	ListMessages(ctx context.Context, req *AgentSessionRequest, opts ...http.CallOption) (rsp *AgentMessageList, err error)
	// ListSessions Old: GET /api/v1/agents/{key}/sessions.
	ListSessions(ctx context.Context, req *AgentSessionListRequest, opts ...http.CallOption) (rsp *AgentSessionList, err error)
	// Update Old: PUT /api/v1/agents/{key}.
	Update(ctx context.Context, req *AgentUpdateRequest, opts ...http.CallOption) (rsp *AgentOk, err error)
}

type AgentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentServiceHTTPClient(client *http.Client) AgentServiceHTTPClient {
	return &AgentServiceHTTPClientImpl{client}
}

// Create Old: POST /api/v1/agents.
func (c *AgentServiceHTTPClientImpl) Create(ctx context.Context, in *AgentInput, opts ...http.CallOption) (*Agent, error) {
	var out Agent
	pattern := "/api/v1/agents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSession Old: POST /api/v1/agents/{key}/sessions.
func (c *AgentServiceHTTPClientImpl) CreateSession(ctx context.Context, in *CreateAgentSessionRequest, opts ...http.CallOption) (*AgentSession, error) {
	var out AgentSession
	pattern := "/api/v1/agent-sessions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceCreateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Old: DELETE /api/v1/agents/{key}.
func (c *AgentServiceHTTPClientImpl) Delete(ctx context.Context, in *AgentKeyRequest, opts ...http.CallOption) (*AgentOk, error) {
	var out AgentOk
	pattern := "/api/v1/agents/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSession Old: DELETE /api/v1/agents/sessions/{sessionId}.
func (c *AgentServiceHTTPClientImpl) DeleteSession(ctx context.Context, in *AgentSessionRequest, opts ...http.CallOption) (*AgentOk, error) {
	var out AgentOk
	pattern := "/api/v1/agent-sessions/{sessionId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceDeleteSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Old: GET /api/v1/agents/{key}.
func (c *AgentServiceHTTPClientImpl) Get(ctx context.Context, in *AgentKeyRequest, opts ...http.CallOption) (*Agent, error) {
	var out Agent
	pattern := "/api/v1/agents/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List Old: GET /api/v1/agents?keyword=.
func (c *AgentServiceHTTPClientImpl) List(ctx context.Context, in *AgentListRequest, opts ...http.CallOption) (*AgentListResponse, error) {
	var out AgentListResponse
	pattern := "/api/v1/agents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMessages Old: GET /api/v1/agents/sessions/{sessionId}/messages.
func (c *AgentServiceHTTPClientImpl) ListMessages(ctx context.Context, in *AgentSessionRequest, opts ...http.CallOption) (*AgentMessageList, error) {
	var out AgentMessageList
	pattern := "/api/v1/agent-sessions/{sessionId}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSessions Old: GET /api/v1/agents/{key}/sessions.
func (c *AgentServiceHTTPClientImpl) ListSessions(ctx context.Context, in *AgentSessionListRequest, opts ...http.CallOption) (*AgentSessionList, error) {
	var out AgentSessionList
	pattern := "/api/v1/agent-sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentServiceListSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Old: PUT /api/v1/agents/{key}.
func (c *AgentServiceHTTPClientImpl) Update(ctx context.Context, in *AgentUpdateRequest, opts ...http.CallOption) (*AgentOk, error) {
	var out AgentOk
	pattern := "/api/v1/agents/{key}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
