// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/archery.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationArcheryServiceClearDefaultConnection = "/baboflow.v1.ArcheryService/ClearDefaultConnection"
const OperationArcheryServiceCreateConnection = "/baboflow.v1.ArcheryService/CreateConnection"
const OperationArcheryServiceDeleteConnection = "/baboflow.v1.ArcheryService/DeleteConnection"
const OperationArcheryServiceGetConnection = "/baboflow.v1.ArcheryService/GetConnection"
const OperationArcheryServiceListConnections = "/baboflow.v1.ArcheryService/ListConnections"
const OperationArcheryServiceListInstances = "/baboflow.v1.ArcheryService/ListInstances"
const OperationArcheryServiceSetDefaultConnection = "/baboflow.v1.ArcheryService/SetDefaultConnection"
const OperationArcheryServiceSyncInstances = "/baboflow.v1.ArcheryService/SyncInstances"
const OperationArcheryServiceTestConnection = "/baboflow.v1.ArcheryService/TestConnection"
const OperationArcheryServiceUpdateConnection = "/baboflow.v1.ArcheryService/UpdateConnection"

type ArcheryServiceHTTPServer interface {
	// ClearDefaultConnection Old: DELETE /api/v1/archery/connections/{id}/default.
	ClearDefaultConnection(context.Context, *ArcheryIdRequest) (*ArcheryOkResponse, error)
	// CreateConnection Old: POST /api/v1/archery/connections.
	CreateConnection(context.Context, *ArcheryConnectionInput) (*ArcheryCreateResponse, error)
	// DeleteConnection Old: DELETE /api/v1/archery/connections/{id}.
	DeleteConnection(context.Context, *ArcheryIdRequest) (*ArcheryOkResponse, error)
	// GetConnection Old: GET /api/v1/archery/connections/{id}.
	GetConnection(context.Context, *ArcheryIdRequest) (*ArcheryConnection, error)
	// ListConnections Old: GET /api/v1/archery/connections.
	ListConnections(context.Context, *Empty) (*ArcheryConnectionList, error)
	// ListInstances Old: GET /api/v1/archery/connections/{id}/instances.
	ListInstances(context.Context, *ArcheryIdRequest) (*ArcheryInstanceList, error)
	// SetDefaultConnection Old: POST /api/v1/archery/connections/{id}/default.
	SetDefaultConnection(context.Context, *ArcheryIdRequest) (*ArcheryOkResponse, error)
	// SyncInstances Old: POST /api/v1/archery/connections/{id}/sync-instances.
	SyncInstances(context.Context, *ArcheryIdRequest) (*ArcheryInstanceList, error)
	// TestConnection Old: POST /api/v1/archery/connections/{id}/test.
	TestConnection(context.Context, *ArcheryIdRequest) (*ArcheryTestResult, error)
	// UpdateConnection Old: PUT /api/v1/archery/connections/{id}.
	UpdateConnection(context.Context, *ArcheryConnectionRequest) (*ArcheryOkResponse, error)
}

func RegisterArcheryServiceHTTPServer(s *http.Server, srv ArcheryServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/archery/connections", _ArcheryService_ListConnections0_HTTP_Handler(srv))
	r.POST("/api/v1/archery/connections", _ArcheryService_CreateConnection0_HTTP_Handler(srv))
	r.GET("/api/v1/archery/connections/{id}", _ArcheryService_GetConnection0_HTTP_Handler(srv))
	r.PUT("/api/v1/archery/connections/{id}", _ArcheryService_UpdateConnection0_HTTP_Handler(srv))
	r.DELETE("/api/v1/archery/connections/{id}", _ArcheryService_DeleteConnection0_HTTP_Handler(srv))
	r.POST("/api/v1/archery/connections/{id}/default", _ArcheryService_SetDefaultConnection0_HTTP_Handler(srv))
	r.DELETE("/api/v1/archery/connections/{id}/default", _ArcheryService_ClearDefaultConnection0_HTTP_Handler(srv))
	r.POST("/api/v1/archery/connections/{id}/test", _ArcheryService_TestConnection0_HTTP_Handler(srv))
	r.GET("/api/v1/archery/connections/{id}/instances", _ArcheryService_ListInstances0_HTTP_Handler(srv))
	r.POST("/api/v1/archery/connections/{id}/sync-instances", _ArcheryService_SyncInstances0_HTTP_Handler(srv))
}

func _ArcheryService_ListConnections0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceListConnections)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConnections(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryConnectionList)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_CreateConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryConnectionInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceCreateConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConnection(ctx, req.(*ArcheryConnectionInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryCreateResponse)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_GetConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceGetConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConnection(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryConnection)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_UpdateConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryConnectionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceUpdateConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConnection(ctx, req.(*ArcheryConnectionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryOkResponse)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_DeleteConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceDeleteConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConnection(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryOkResponse)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_SetDefaultConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceSetDefaultConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDefaultConnection(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryOkResponse)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_ClearDefaultConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceClearDefaultConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearDefaultConnection(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryOkResponse)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_TestConnection0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceTestConnection)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestConnection(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryTestResult)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_ListInstances0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceListInstances)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInstances(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryInstanceList)
		return ctx.Result(200, reply)
	}
}

func _ArcheryService_SyncInstances0_HTTP_Handler(srv ArcheryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArcheryIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArcheryServiceSyncInstances)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncInstances(ctx, req.(*ArcheryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArcheryInstanceList)
		return ctx.Result(200, reply)
	}
}

type ArcheryServiceHTTPClient interface {
	// ClearDefaultConnection Old: DELETE /api/v1/archery/connections/{id}/default.
	ClearDefaultConnection(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryOkResponse, err error)
	// CreateConnection Old: POST /api/v1/archery/connections.
	CreateConnection(ctx context.Context, req *ArcheryConnectionInput, opts ...http.CallOption) (rsp *ArcheryCreateResponse, err error)
	// DeleteConnection Old: DELETE /api/v1/archery/connections/{id}.
	DeleteConnection(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryOkResponse, err error)
	// GetConnection Old: GET /api/v1/archery/connections/{id}.
	GetConnection(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryConnection, err error)
	// ListConnections Old: GET /api/v1/archery/connections.
	ListConnections(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ArcheryConnectionList, err error)
	// ListInstances Old: GET /api/v1/archery/connections/{id}/instances.
	ListInstances(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryInstanceList, err error)
	// SetDefaultConnection Old: POST /api/v1/archery/connections/{id}/default.
	SetDefaultConnection(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryOkResponse, err error)
	// SyncInstances Old: POST /api/v1/archery/connections/{id}/sync-instances.
	SyncInstances(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryInstanceList, err error)
	// TestConnection Old: POST /api/v1/archery/connections/{id}/test.
	TestConnection(ctx context.Context, req *ArcheryIdRequest, opts ...http.CallOption) (rsp *ArcheryTestResult, err error)
	// UpdateConnection Old: PUT /api/v1/archery/connections/{id}.
	UpdateConnection(ctx context.Context, req *ArcheryConnectionRequest, opts ...http.CallOption) (rsp *ArcheryOkResponse, err error)
}

type ArcheryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArcheryServiceHTTPClient(client *http.Client) ArcheryServiceHTTPClient {
	return &ArcheryServiceHTTPClientImpl{client}
}

// ClearDefaultConnection Old: DELETE /api/v1/archery/connections/{id}/default.
func (c *ArcheryServiceHTTPClientImpl) ClearDefaultConnection(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryOkResponse, error) {
	var out ArcheryOkResponse
	pattern := "/api/v1/archery/connections/{id}/default"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArcheryServiceClearDefaultConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateConnection Old: POST /api/v1/archery/connections.
func (c *ArcheryServiceHTTPClientImpl) CreateConnection(ctx context.Context, in *ArcheryConnectionInput, opts ...http.CallOption) (*ArcheryCreateResponse, error) {
	var out ArcheryCreateResponse
	pattern := "/api/v1/archery/connections"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArcheryServiceCreateConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteConnection Old: DELETE /api/v1/archery/connections/{id}.
func (c *ArcheryServiceHTTPClientImpl) DeleteConnection(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryOkResponse, error) {
	var out ArcheryOkResponse
	pattern := "/api/v1/archery/connections/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArcheryServiceDeleteConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetConnection Old: GET /api/v1/archery/connections/{id}.
func (c *ArcheryServiceHTTPClientImpl) GetConnection(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryConnection, error) {
	var out ArcheryConnection
	pattern := "/api/v1/archery/connections/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArcheryServiceGetConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListConnections Old: GET /api/v1/archery/connections.
func (c *ArcheryServiceHTTPClientImpl) ListConnections(ctx context.Context, in *Empty, opts ...http.CallOption) (*ArcheryConnectionList, error) {
	var out ArcheryConnectionList
	pattern := "/api/v1/archery/connections"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArcheryServiceListConnections))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListInstances Old: GET /api/v1/archery/connections/{id}/instances.
func (c *ArcheryServiceHTTPClientImpl) ListInstances(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryInstanceList, error) {
	var out ArcheryInstanceList
	pattern := "/api/v1/archery/connections/{id}/instances"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArcheryServiceListInstances))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetDefaultConnection Old: POST /api/v1/archery/connections/{id}/default.
func (c *ArcheryServiceHTTPClientImpl) SetDefaultConnection(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryOkResponse, error) {
	var out ArcheryOkResponse
	pattern := "/api/v1/archery/connections/{id}/default"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArcheryServiceSetDefaultConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SyncInstances Old: POST /api/v1/archery/connections/{id}/sync-instances.
func (c *ArcheryServiceHTTPClientImpl) SyncInstances(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryInstanceList, error) {
	var out ArcheryInstanceList
	pattern := "/api/v1/archery/connections/{id}/sync-instances"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArcheryServiceSyncInstances))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestConnection Old: POST /api/v1/archery/connections/{id}/test.
func (c *ArcheryServiceHTTPClientImpl) TestConnection(ctx context.Context, in *ArcheryIdRequest, opts ...http.CallOption) (*ArcheryTestResult, error) {
	var out ArcheryTestResult
	pattern := "/api/v1/archery/connections/{id}/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArcheryServiceTestConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateConnection Old: PUT /api/v1/archery/connections/{id}.
func (c *ArcheryServiceHTTPClientImpl) UpdateConnection(ctx context.Context, in *ArcheryConnectionRequest, opts ...http.CallOption) (*ArcheryOkResponse, error) {
	var out ArcheryOkResponse
	pattern := "/api/v1/archery/connections/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArcheryServiceUpdateConnection))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
