// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/audit.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuditServiceList = "/baboflow.v1.AuditService/List"

type AuditServiceHTTPServer interface {
	// List Old: GET /api/v1/audit?action=&userId=&page=&pageSize=.
	List(context.Context, *AuditLogListRequest) (*AuditLogListResponse, error)
}

func RegisterAuditServiceHTTPServer(s *http.Server, srv AuditServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/audit-logs", _AuditService_List1_HTTP_Handler(srv))
}

func _AuditService_List1_HTTP_Handler(srv AuditServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AuditLogListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuditServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*AuditLogListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AuditLogListResponse)
		return ctx.Result(200, reply)
	}
}

type AuditServiceHTTPClient interface {
	// List Old: GET /api/v1/audit?action=&userId=&page=&pageSize=.
	List(ctx context.Context, req *AuditLogListRequest, opts ...http.CallOption) (rsp *AuditLogListResponse, err error)
}

type AuditServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuditServiceHTTPClient(client *http.Client) AuditServiceHTTPClient {
	return &AuditServiceHTTPClientImpl{client}
}

// List Old: GET /api/v1/audit?action=&userId=&page=&pageSize=.
func (c *AuditServiceHTTPClientImpl) List(ctx context.Context, in *AuditLogListRequest, opts ...http.CallOption) (*AuditLogListResponse, error) {
	var out AuditLogListResponse
	pattern := "/api/v1/audit-logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuditServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
