// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/audit.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      string                 `protobuf:"bytes,5,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Detail        *structpb.Struct       `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_baboflow_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditLog) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditLog) GetDetail() *structpb.Struct {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *AuditLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuditLogListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogListRequest) Reset() {
	*x = AuditLogListRequest{}
	mi := &file_baboflow_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogListRequest) ProtoMessage() {}

func (x *AuditLogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogListRequest.ProtoReflect.Descriptor instead.
func (*AuditLogListRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditLogListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *AuditLogListRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuditLogListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AuditLog            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogListResponse) Reset() {
	*x = AuditLogListResponse{}
	mi := &file_baboflow_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogListResponse) ProtoMessage() {}

func (x *AuditLogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogListResponse.ProtoReflect.Descriptor instead.
func (*AuditLogListResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLogListResponse) GetList() []*AuditLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AuditLogListResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_baboflow_v1_audit_proto protoreflect.FileDescriptor

const file_baboflow_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x17baboflow/v1/audit.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18baboflow/v1/common.proto\"\xe5\x01\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"targetType\x18\x04 \x01(\tR\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x05 \x01(\tR\btargetId\x12/\n" +
	"\x06detail\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06detail\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\"s\n" +
	"\x13AuditLogListRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.baboflow.v1.PageRequestR\x04page\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"p\n" +
	"\x14AuditLogListResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.baboflow.v1.AuditLogR\x04list\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.baboflow.v1.PageResponseR\x04page2w\n" +
	"\fAuditService\x12g\n" +
	"\x04List\x12 .baboflow.v1.AuditLogListRequest\x1a!.baboflow.v1.AuditLogListResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/audit-logsB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_audit_proto_rawDescOnce sync.Once
	file_baboflow_v1_audit_proto_rawDescData []byte
)

func file_baboflow_v1_audit_proto_rawDescGZIP() []byte {
	file_baboflow_v1_audit_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_audit_proto_rawDesc), len(file_baboflow_v1_audit_proto_rawDesc)))
	})
	return file_baboflow_v1_audit_proto_rawDescData
}

var file_baboflow_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_baboflow_v1_audit_proto_goTypes = []any{
	(*AuditLog)(nil),             // 0: baboflow.v1.AuditLog
	(*AuditLogListRequest)(nil),  // 1: baboflow.v1.AuditLogListRequest
	(*AuditLogListResponse)(nil), // 2: baboflow.v1.AuditLogListResponse
	(*structpb.Struct)(nil),      // 3: google.protobuf.Struct
	(*PageRequest)(nil),          // 4: baboflow.v1.PageRequest
	(*PageResponse)(nil),         // 5: baboflow.v1.PageResponse
}
var file_baboflow_v1_audit_proto_depIdxs = []int32{
	3, // 0: baboflow.v1.AuditLog.detail:type_name -> google.protobuf.Struct
	4, // 1: baboflow.v1.AuditLogListRequest.page:type_name -> baboflow.v1.PageRequest
	0, // 2: baboflow.v1.AuditLogListResponse.list:type_name -> baboflow.v1.AuditLog
	5, // 3: baboflow.v1.AuditLogListResponse.page:type_name -> baboflow.v1.PageResponse
	1, // 4: baboflow.v1.AuditService.List:input_type -> baboflow.v1.AuditLogListRequest
	2, // 5: baboflow.v1.AuditService.List:output_type -> baboflow.v1.AuditLogListResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baboflow_v1_audit_proto_init() }
func file_baboflow_v1_audit_proto_init() {
	if File_baboflow_v1_audit_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_audit_proto_rawDesc), len(file_baboflow_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_audit_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_audit_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_audit_proto_msgTypes,
	}.Build()
	File_baboflow_v1_audit_proto = out.File
	file_baboflow_v1_audit_proto_goTypes = nil
	file_baboflow_v1_audit_proto_depIdxs = nil
}
