// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	MustChangePwd bool                   `protobuf:"varint,4,opt,name=mustChangePwd,proto3" json:"mustChangePwd,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_baboflow_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetMustChangePwd() bool {
	if x != nil {
		return x.MustChangePwd
	}
	return false
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_baboflow_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_baboflow_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_baboflow_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_baboflow_v1_auth_proto protoreflect.FileDescriptor

const file_baboflow_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16baboflow/v1/auth.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18baboflow/v1/common.proto\"\xb0\x01\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12 \n" +
	"\vdisplayName\x18\x03 \x01(\tR\vdisplayName\x12$\n" +
	"\rmustChangePwd\x18\x04 \x01(\bR\rmustChangePwd\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\" \n" +
	"\x0eLogoutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"[\n" +
	"\x15ChangePasswordRequest\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword2\xfc\x02\n" +
	"\vAuthService\x12T\n" +
	"\x05Login\x12\x19.baboflow.v1.LoginRequest\x1a\x11.baboflow.v1.User\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12Y\n" +
	"\x06Logout\x12\x12.baboflow.v1.Empty\x1a\x1b.baboflow.v1.LogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12G\n" +
	"\x05GetMe\x12\x12.baboflow.v1.Empty\x1a\x11.baboflow.v1.User\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/auth/me\x12s\n" +
	"\x0eChangePassword\x12\".baboflow.v1.ChangePasswordRequest\x1a\x1b.baboflow.v1.LogoutResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/auth/passwordB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_auth_proto_rawDescOnce sync.Once
	file_baboflow_v1_auth_proto_rawDescData []byte
)

func file_baboflow_v1_auth_proto_rawDescGZIP() []byte {
	file_baboflow_v1_auth_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_auth_proto_rawDesc), len(file_baboflow_v1_auth_proto_rawDesc)))
	})
	return file_baboflow_v1_auth_proto_rawDescData
}

var file_baboflow_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_baboflow_v1_auth_proto_goTypes = []any{
	(*User)(nil),                  // 0: baboflow.v1.User
	(*LoginRequest)(nil),          // 1: baboflow.v1.LoginRequest
	(*LogoutResponse)(nil),        // 2: baboflow.v1.LogoutResponse
	(*ChangePasswordRequest)(nil), // 3: baboflow.v1.ChangePasswordRequest
	(*Empty)(nil),                 // 4: baboflow.v1.Empty
}
var file_baboflow_v1_auth_proto_depIdxs = []int32{
	1, // 0: baboflow.v1.AuthService.Login:input_type -> baboflow.v1.LoginRequest
	4, // 1: baboflow.v1.AuthService.Logout:input_type -> baboflow.v1.Empty
	4, // 2: baboflow.v1.AuthService.GetMe:input_type -> baboflow.v1.Empty
	3, // 3: baboflow.v1.AuthService.ChangePassword:input_type -> baboflow.v1.ChangePasswordRequest
	0, // 4: baboflow.v1.AuthService.Login:output_type -> baboflow.v1.User
	2, // 5: baboflow.v1.AuthService.Logout:output_type -> baboflow.v1.LogoutResponse
	0, // 6: baboflow.v1.AuthService.GetMe:output_type -> baboflow.v1.User
	2, // 7: baboflow.v1.AuthService.ChangePassword:output_type -> baboflow.v1.LogoutResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_baboflow_v1_auth_proto_init() }
func file_baboflow_v1_auth_proto_init() {
	if File_baboflow_v1_auth_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_auth_proto_rawDesc), len(file_baboflow_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_auth_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_auth_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_auth_proto_msgTypes,
	}.Build()
	File_baboflow_v1_auth_proto = out.File
	file_baboflow_v1_auth_proto_goTypes = nil
	file_baboflow_v1_auth_proto_depIdxs = nil
}
