// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/board.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_baboflow_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Board) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Board) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BoardTaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardTaskResult) Reset() {
	*x = BoardTaskResult{}
	mi := &file_baboflow_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardTaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardTaskResult) ProtoMessage() {}

func (x *BoardTaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardTaskResult.ProtoReflect.Descriptor instead.
func (*BoardTaskResult) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardTaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *BoardTaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BoardTask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ColumnId        int64                  `protobuf:"varint,2,opt,name=columnId,proto3" json:"columnId,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Payload         string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AssignedChainId string                 `protobuf:"bytes,6,opt,name=assignedChainId,proto3" json:"assignedChainId,omitempty"`
	RunId           int64                  `protobuf:"varint,7,opt,name=runId,proto3" json:"runId,omitempty"`
	Result          *BoardTaskResult       `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	RetryMax        int32                  `protobuf:"varint,9,opt,name=retryMax,proto3" json:"retryMax,omitempty"`
	RetryCount      int32                  `protobuf:"varint,10,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	TimeoutSec      int32                  `protobuf:"varint,11,opt,name=timeoutSec,proto3" json:"timeoutSec,omitempty"`
	Sort            int64                  `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BoardTask) Reset() {
	*x = BoardTask{}
	mi := &file_baboflow_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardTask) ProtoMessage() {}

func (x *BoardTask) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardTask.ProtoReflect.Descriptor instead.
func (*BoardTask) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *BoardTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BoardTask) GetColumnId() int64 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

func (x *BoardTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BoardTask) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *BoardTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BoardTask) GetAssignedChainId() string {
	if x != nil {
		return x.AssignedChainId
	}
	return ""
}

func (x *BoardTask) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *BoardTask) GetResult() *BoardTaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BoardTask) GetRetryMax() int32 {
	if x != nil {
		return x.RetryMax
	}
	return 0
}

func (x *BoardTask) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *BoardTask) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *BoardTask) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *BoardTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BoardTask) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BoardColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       int64                  `protobuf:"varint,2,opt,name=boardId,proto3" json:"boardId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int64                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Tasks         []*BoardTask           `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardColumn) Reset() {
	*x = BoardColumn{}
	mi := &file_baboflow_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardColumn) ProtoMessage() {}

func (x *BoardColumn) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardColumn.ProtoReflect.Descriptor instead.
func (*BoardColumn) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *BoardColumn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BoardColumn) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *BoardColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardColumn) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *BoardColumn) GetTasks() []*BoardTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type BoardDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Columns       []*BoardColumn         `protobuf:"bytes,6,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardDetail) Reset() {
	*x = BoardDetail{}
	mi := &file_baboflow_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardDetail) ProtoMessage() {}

func (x *BoardDetail) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardDetail.ProtoReflect.Descriptor instead.
func (*BoardDetail) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *BoardDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BoardDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BoardDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *BoardDetail) GetColumns() []*BoardColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

type BoardInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardInput) Reset() {
	*x = BoardInput{}
	mi := &file_baboflow_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardInput) ProtoMessage() {}

func (x *BoardInput) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardInput.ProtoReflect.Descriptor instead.
func (*BoardInput) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *BoardInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardRequest) Reset() {
	*x = BoardRequest{}
	mi := &file_baboflow_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardRequest) ProtoMessage() {}

func (x *BoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardRequest.ProtoReflect.Descriptor instead.
func (*BoardRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{6}
}

func (x *BoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BoardIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardIdRequest) Reset() {
	*x = BoardIdRequest{}
	mi := &file_baboflow_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardIdRequest) ProtoMessage() {}

func (x *BoardIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardIdRequest.ProtoReflect.Descriptor instead.
func (*BoardIdRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *BoardIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BoardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Board               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardList) Reset() {
	*x = BoardList{}
	mi := &file_baboflow_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardList) ProtoMessage() {}

func (x *BoardList) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardList.ProtoReflect.Descriptor instead.
func (*BoardList) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{8}
}

func (x *BoardList) GetList() []*Board {
	if x != nil {
		return x.List
	}
	return nil
}

type ColumnInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       int64                  `protobuf:"varint,1,opt,name=boardId,proto3" json:"boardId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int64                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInput) Reset() {
	*x = ColumnInput{}
	mi := &file_baboflow_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInput) ProtoMessage() {}

func (x *ColumnInput) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInput.ProtoReflect.Descriptor instead.
func (*ColumnInput) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnInput) GetBoardId() int64 {
	if x != nil {
		return x.BoardId
	}
	return 0
}

func (x *ColumnInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnInput) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ColumnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sort          int64                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnRequest) Reset() {
	*x = ColumnRequest{}
	mi := &file_baboflow_v1_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnRequest) ProtoMessage() {}

func (x *ColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnRequest.ProtoReflect.Descriptor instead.
func (*ColumnRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{10}
}

func (x *ColumnRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ColumnRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnRequest) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type TaskInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ColumnId        int64                  `protobuf:"varint,1,opt,name=columnId,proto3" json:"columnId,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Payload         string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	AssignedChainId string                 `protobuf:"bytes,4,opt,name=assignedChainId,proto3" json:"assignedChainId,omitempty"`
	RetryMax        int32                  `protobuf:"varint,5,opt,name=retryMax,proto3" json:"retryMax,omitempty"`
	TimeoutSec      int32                  `protobuf:"varint,6,opt,name=timeoutSec,proto3" json:"timeoutSec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskInput) Reset() {
	*x = TaskInput{}
	mi := &file_baboflow_v1_board_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInput) ProtoMessage() {}

func (x *TaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInput.ProtoReflect.Descriptor instead.
func (*TaskInput) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{11}
}

func (x *TaskInput) GetColumnId() int64 {
	if x != nil {
		return x.ColumnId
	}
	return 0
}

func (x *TaskInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskInput) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TaskInput) GetAssignedChainId() string {
	if x != nil {
		return x.AssignedChainId
	}
	return ""
}

func (x *TaskInput) GetRetryMax() int32 {
	if x != nil {
		return x.RetryMax
	}
	return 0
}

func (x *TaskInput) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type TaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Payload         string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	AssignedChainId string                 `protobuf:"bytes,4,opt,name=assignedChainId,proto3" json:"assignedChainId,omitempty"`
	RetryMax        int32                  `protobuf:"varint,5,opt,name=retryMax,proto3" json:"retryMax,omitempty"`
	TimeoutSec      int32                  `protobuf:"varint,6,opt,name=timeoutSec,proto3" json:"timeoutSec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_baboflow_v1_board_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{12}
}

func (x *TaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TaskRequest) GetAssignedChainId() string {
	if x != nil {
		return x.AssignedChainId
	}
	return ""
}

func (x *TaskRequest) GetRetryMax() int32 {
	if x != nil {
		return x.RetryMax
	}
	return 0
}

func (x *TaskRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type MoveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ToColumnId    int64                  `protobuf:"varint,2,opt,name=toColumnId,proto3" json:"toColumnId,omitempty"`
	ToSort        int64                  `protobuf:"varint,3,opt,name=toSort,proto3" json:"toSort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTaskRequest) Reset() {
	*x = MoveTaskRequest{}
	mi := &file_baboflow_v1_board_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTaskRequest) ProtoMessage() {}

func (x *MoveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTaskRequest.ProtoReflect.Descriptor instead.
func (*MoveTaskRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{13}
}

func (x *MoveTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveTaskRequest) GetToColumnId() int64 {
	if x != nil {
		return x.ToColumnId
	}
	return 0
}

func (x *MoveTaskRequest) GetToSort() int64 {
	if x != nil {
		return x.ToSort
	}
	return 0
}

type BoardOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardOk) Reset() {
	*x = BoardOk{}
	mi := &file_baboflow_v1_board_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardOk) ProtoMessage() {}

func (x *BoardOk) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_board_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardOk.ProtoReflect.Descriptor instead.
func (*BoardOk) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_board_proto_rawDescGZIP(), []int{14}
}

func (x *BoardOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_baboflow_v1_board_proto protoreflect.FileDescriptor

const file_baboflow_v1_board_proto_rawDesc = "" +
	"\n" +
	"\x17baboflow/v1/board.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18baboflow/v1/common.proto\"\x89\x01\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"?\n" +
	"\x0fBoardTaskResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa1\x03\n" +
	"\tBoardTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bcolumnId\x18\x02 \x01(\x03R\bcolumnId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12(\n" +
	"\x0fassignedChainId\x18\x06 \x01(\tR\x0fassignedChainId\x12\x14\n" +
	"\x05runId\x18\a \x01(\x03R\x05runId\x124\n" +
	"\x06result\x18\b \x01(\v2\x1c.baboflow.v1.BoardTaskResultR\x06result\x12\x1a\n" +
	"\bretryMax\x18\t \x01(\x05R\bretryMax\x12\x1e\n" +
	"\n" +
	"retryCount\x18\n" +
	" \x01(\x05R\n" +
	"retryCount\x12\x1e\n" +
	"\n" +
	"timeoutSec\x18\v \x01(\x05R\n" +
	"timeoutSec\x12\x12\n" +
	"\x04sort\x18\f \x01(\x03R\x04sort\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\tR\tupdatedAt\"\x8d\x01\n" +
	"\vBoardColumn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aboardId\x18\x02 \x01(\x03R\aboardId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x03R\x04sort\x12,\n" +
	"\x05tasks\x18\x05 \x03(\v2\x16.baboflow.v1.BoardTaskR\x05tasks\"\xc3\x01\n" +
	"\vBoardDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\x122\n" +
	"\acolumns\x18\x06 \x03(\v2\x18.baboflow.v1.BoardColumnR\acolumns\"B\n" +
	"\n" +
	"BoardInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"T\n" +
	"\fBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\" \n" +
	"\x0eBoardIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\tBoardList\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.baboflow.v1.BoardR\x04list\"O\n" +
	"\vColumnInput\x12\x18\n" +
	"\aboardId\x18\x01 \x01(\x03R\aboardId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x03R\x04sort\"G\n" +
	"\rColumnRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x03R\x04sort\"\xbd\x01\n" +
	"\tTaskInput\x12\x1a\n" +
	"\bcolumnId\x18\x01 \x01(\x03R\bcolumnId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12(\n" +
	"\x0fassignedChainId\x18\x04 \x01(\tR\x0fassignedChainId\x12\x1a\n" +
	"\bretryMax\x18\x05 \x01(\x05R\bretryMax\x12\x1e\n" +
	"\n" +
	"timeoutSec\x18\x06 \x01(\x05R\n" +
	"timeoutSec\"\xb3\x01\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12(\n" +
	"\x0fassignedChainId\x18\x04 \x01(\tR\x0fassignedChainId\x12\x1a\n" +
	"\bretryMax\x18\x05 \x01(\x05R\bretryMax\x12\x1e\n" +
	"\n" +
	"timeoutSec\x18\x06 \x01(\x05R\n" +
	"timeoutSec\"Y\n" +
	"\x0fMoveTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"toColumnId\x18\x02 \x01(\x03R\n" +
	"toColumnId\x12\x16\n" +
	"\x06toSort\x18\x03 \x01(\x03R\x06toSort\"\x19\n" +
	"\aBoardOk\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd3\t\n" +
	"\fBoardService\x12J\n" +
	"\x04List\x12\x12.baboflow.v1.Empty\x1a\x16.baboflow.v1.BoardList\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/boards\x12P\n" +
	"\x06Create\x12\x17.baboflow.v1.BoardInput\x1a\x12.baboflow.v1.Board\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/boards\x12Y\n" +
	"\x03Get\x12\x1b.baboflow.v1.BoardIdRequest\x1a\x18.baboflow.v1.BoardDetail\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/boards/{id}\x12Y\n" +
	"\x06Update\x12\x19.baboflow.v1.BoardRequest\x1a\x14.baboflow.v1.BoardOk\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/v1/boards/{id}\x12X\n" +
	"\x06Delete\x12\x1b.baboflow.v1.BoardIdRequest\x1a\x14.baboflow.v1.BoardOk\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/boards/{id}\x12d\n" +
	"\fCreateColumn\x12\x18.baboflow.v1.ColumnInput\x1a\x18.baboflow.v1.BoardColumn\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/board-columns\x12g\n" +
	"\fUpdateColumn\x12\x1a.baboflow.v1.ColumnRequest\x1a\x14.baboflow.v1.BoardOk\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/api/v1/board-columns/{id}\x12e\n" +
	"\fDeleteColumn\x12\x1b.baboflow.v1.BoardIdRequest\x1a\x14.baboflow.v1.BoardOk\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/board-columns/{id}\x12V\n" +
	"\n" +
	"CreateTask\x12\x16.baboflow.v1.TaskInput\x1a\x16.baboflow.v1.BoardTask\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12[\n" +
	"\n" +
	"UpdateTask\x12\x18.baboflow.v1.TaskRequest\x1a\x14.baboflow.v1.BoardOk\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/tasks/{id}\x12[\n" +
	"\n" +
	"DeleteTask\x12\x1b.baboflow.v1.BoardIdRequest\x1a\x14.baboflow.v1.BoardOk\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/tasks/{id}\x12b\n" +
	"\bMoveTask\x12\x1c.baboflow.v1.MoveTaskRequest\x1a\x14.baboflow.v1.BoardOk\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/tasks/{id}/move\x12i\n" +
	"\vTriggerTask\x12\x1b.baboflow.v1.BoardIdRequest\x1a\x16.baboflow.v1.BoardTask\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/tasks/{id}/triggerB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_board_proto_rawDescOnce sync.Once
	file_baboflow_v1_board_proto_rawDescData []byte
)

func file_baboflow_v1_board_proto_rawDescGZIP() []byte {
	file_baboflow_v1_board_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_board_proto_rawDesc), len(file_baboflow_v1_board_proto_rawDesc)))
	})
	return file_baboflow_v1_board_proto_rawDescData
}

var file_baboflow_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_baboflow_v1_board_proto_goTypes = []any{
	(*Board)(nil),           // 0: baboflow.v1.Board
	(*BoardTaskResult)(nil), // 1: baboflow.v1.BoardTaskResult
	(*BoardTask)(nil),       // 2: baboflow.v1.BoardTask
	(*BoardColumn)(nil),     // 3: baboflow.v1.BoardColumn
	(*BoardDetail)(nil),     // 4: baboflow.v1.BoardDetail
	(*BoardInput)(nil),      // 5: baboflow.v1.BoardInput
	(*BoardRequest)(nil),    // 6: baboflow.v1.BoardRequest
	(*BoardIdRequest)(nil),  // 7: baboflow.v1.BoardIdRequest
	(*BoardList)(nil),       // 8: baboflow.v1.BoardList
	(*ColumnInput)(nil),     // 9: baboflow.v1.ColumnInput
	(*ColumnRequest)(nil),   // 10: baboflow.v1.ColumnRequest
	(*TaskInput)(nil),       // 11: baboflow.v1.TaskInput
	(*TaskRequest)(nil),     // 12: baboflow.v1.TaskRequest
	(*MoveTaskRequest)(nil), // 13: baboflow.v1.MoveTaskRequest
	(*BoardOk)(nil),         // 14: baboflow.v1.BoardOk
	(*Empty)(nil),           // 15: baboflow.v1.Empty
}
var file_baboflow_v1_board_proto_depIdxs = []int32{
	1,  // 0: baboflow.v1.BoardTask.result:type_name -> baboflow.v1.BoardTaskResult
	2,  // 1: baboflow.v1.BoardColumn.tasks:type_name -> baboflow.v1.BoardTask
	3,  // 2: baboflow.v1.BoardDetail.columns:type_name -> baboflow.v1.BoardColumn
	0,  // 3: baboflow.v1.BoardList.list:type_name -> baboflow.v1.Board
	15, // 4: baboflow.v1.BoardService.List:input_type -> baboflow.v1.Empty
	5,  // 5: baboflow.v1.BoardService.Create:input_type -> baboflow.v1.BoardInput
	7,  // 6: baboflow.v1.BoardService.Get:input_type -> baboflow.v1.BoardIdRequest
	6,  // 7: baboflow.v1.BoardService.Update:input_type -> baboflow.v1.BoardRequest
	7,  // 8: baboflow.v1.BoardService.Delete:input_type -> baboflow.v1.BoardIdRequest
	9,  // 9: baboflow.v1.BoardService.CreateColumn:input_type -> baboflow.v1.ColumnInput
	10, // 10: baboflow.v1.BoardService.UpdateColumn:input_type -> baboflow.v1.ColumnRequest
	7,  // 11: baboflow.v1.BoardService.DeleteColumn:input_type -> baboflow.v1.BoardIdRequest
	11, // 12: baboflow.v1.BoardService.CreateTask:input_type -> baboflow.v1.TaskInput
	12, // 13: baboflow.v1.BoardService.UpdateTask:input_type -> baboflow.v1.TaskRequest
	7,  // 14: baboflow.v1.BoardService.DeleteTask:input_type -> baboflow.v1.BoardIdRequest
	13, // 15: baboflow.v1.BoardService.MoveTask:input_type -> baboflow.v1.MoveTaskRequest
	7,  // 16: baboflow.v1.BoardService.TriggerTask:input_type -> baboflow.v1.BoardIdRequest
	8,  // 17: baboflow.v1.BoardService.List:output_type -> baboflow.v1.BoardList
	0,  // 18: baboflow.v1.BoardService.Create:output_type -> baboflow.v1.Board
	4,  // 19: baboflow.v1.BoardService.Get:output_type -> baboflow.v1.BoardDetail
	14, // 20: baboflow.v1.BoardService.Update:output_type -> baboflow.v1.BoardOk
	14, // 21: baboflow.v1.BoardService.Delete:output_type -> baboflow.v1.BoardOk
	3,  // 22: baboflow.v1.BoardService.CreateColumn:output_type -> baboflow.v1.BoardColumn
	14, // 23: baboflow.v1.BoardService.UpdateColumn:output_type -> baboflow.v1.BoardOk
	14, // 24: baboflow.v1.BoardService.DeleteColumn:output_type -> baboflow.v1.BoardOk
	2,  // 25: baboflow.v1.BoardService.CreateTask:output_type -> baboflow.v1.BoardTask
	14, // 26: baboflow.v1.BoardService.UpdateTask:output_type -> baboflow.v1.BoardOk
	14, // 27: baboflow.v1.BoardService.DeleteTask:output_type -> baboflow.v1.BoardOk
	14, // 28: baboflow.v1.BoardService.MoveTask:output_type -> baboflow.v1.BoardOk
	2,  // 29: baboflow.v1.BoardService.TriggerTask:output_type -> baboflow.v1.BoardTask
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_baboflow_v1_board_proto_init() }
func file_baboflow_v1_board_proto_init() {
	if File_baboflow_v1_board_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_board_proto_rawDesc), len(file_baboflow_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_board_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_board_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_board_proto_msgTypes,
	}.Build()
	File_baboflow_v1_board_proto = out.File
	file_baboflow_v1_board_proto_goTypes = nil
	file_baboflow_v1_board_proto_depIdxs = nil
}
