// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/board.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoardService_List_FullMethodName         = "/baboflow.v1.BoardService/List"
	BoardService_Create_FullMethodName       = "/baboflow.v1.BoardService/Create"
	BoardService_Get_FullMethodName          = "/baboflow.v1.BoardService/Get"
	BoardService_Update_FullMethodName       = "/baboflow.v1.BoardService/Update"
	BoardService_Delete_FullMethodName       = "/baboflow.v1.BoardService/Delete"
	BoardService_CreateColumn_FullMethodName = "/baboflow.v1.BoardService/CreateColumn"
	BoardService_UpdateColumn_FullMethodName = "/baboflow.v1.BoardService/UpdateColumn"
	BoardService_DeleteColumn_FullMethodName = "/baboflow.v1.BoardService/DeleteColumn"
	BoardService_CreateTask_FullMethodName   = "/baboflow.v1.BoardService/CreateTask"
	BoardService_UpdateTask_FullMethodName   = "/baboflow.v1.BoardService/UpdateTask"
	BoardService_DeleteTask_FullMethodName   = "/baboflow.v1.BoardService/DeleteTask"
	BoardService_MoveTask_FullMethodName     = "/baboflow.v1.BoardService/MoveTask"
	BoardService_TriggerTask_FullMethodName  = "/baboflow.v1.BoardService/TriggerTask"
)

// BoardServiceClient is the client API for BoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoardServiceClient interface {
	// Old: GET /api/v1/boards.
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoardList, error)
	// Old: POST /api/v1/boards.
	Create(ctx context.Context, in *BoardInput, opts ...grpc.CallOption) (*Board, error)
	// Old: GET /api/v1/boards/{id}.
	Get(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardDetail, error)
	// Old: PUT /api/v1/boards/{id}.
	Update(ctx context.Context, in *BoardRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: DELETE /api/v1/boards/{id}.
	Delete(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: POST /api/v1/boards/{id}/columns.
	CreateColumn(ctx context.Context, in *ColumnInput, opts ...grpc.CallOption) (*BoardColumn, error)
	// Old: PUT /api/v1/boards/columns/{id}.
	UpdateColumn(ctx context.Context, in *ColumnRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: DELETE /api/v1/boards/columns/{id}.
	DeleteColumn(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: POST /api/v1/boards/columns/{columnId}/tasks.
	CreateTask(ctx context.Context, in *TaskInput, opts ...grpc.CallOption) (*BoardTask, error)
	// Old: PUT /api/v1/tasks/{id}.
	UpdateTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: DELETE /api/v1/tasks/{id}.
	DeleteTask(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: POST /api/v1/tasks/{id}/move.
	MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*BoardOk, error)
	// Old: POST /api/v1/tasks/{id}/trigger.
	TriggerTask(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardTask, error)
}

type boardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoardServiceClient(cc grpc.ClientConnInterface) BoardServiceClient {
	return &boardServiceClient{cc}
}

func (c *boardServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BoardList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardList)
	err := c.cc.Invoke(ctx, BoardService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) Create(ctx context.Context, in *BoardInput, opts ...grpc.CallOption) (*Board, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Board)
	err := c.cc.Invoke(ctx, BoardService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) Get(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardDetail)
	err := c.cc.Invoke(ctx, BoardService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) Update(ctx context.Context, in *BoardRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) Delete(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) CreateColumn(ctx context.Context, in *ColumnInput, opts ...grpc.CallOption) (*BoardColumn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardColumn)
	err := c.cc.Invoke(ctx, BoardService_CreateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) UpdateColumn(ctx context.Context, in *ColumnRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_UpdateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) DeleteColumn(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_DeleteColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) CreateTask(ctx context.Context, in *TaskInput, opts ...grpc.CallOption) (*BoardTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardTask)
	err := c.cc.Invoke(ctx, BoardService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) UpdateTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) DeleteTask(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*BoardOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardOk)
	err := c.cc.Invoke(ctx, BoardService_MoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) TriggerTask(ctx context.Context, in *BoardIdRequest, opts ...grpc.CallOption) (*BoardTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardTask)
	err := c.cc.Invoke(ctx, BoardService_TriggerTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardServiceServer is the server API for BoardService service.
// All implementations must embed UnimplementedBoardServiceServer
// for forward compatibility.
type BoardServiceServer interface {
	// Old: GET /api/v1/boards.
	List(context.Context, *Empty) (*BoardList, error)
	// Old: POST /api/v1/boards.
	Create(context.Context, *BoardInput) (*Board, error)
	// Old: GET /api/v1/boards/{id}.
	Get(context.Context, *BoardIdRequest) (*BoardDetail, error)
	// Old: PUT /api/v1/boards/{id}.
	Update(context.Context, *BoardRequest) (*BoardOk, error)
	// Old: DELETE /api/v1/boards/{id}.
	Delete(context.Context, *BoardIdRequest) (*BoardOk, error)
	// Old: POST /api/v1/boards/{id}/columns.
	CreateColumn(context.Context, *ColumnInput) (*BoardColumn, error)
	// Old: PUT /api/v1/boards/columns/{id}.
	UpdateColumn(context.Context, *ColumnRequest) (*BoardOk, error)
	// Old: DELETE /api/v1/boards/columns/{id}.
	DeleteColumn(context.Context, *BoardIdRequest) (*BoardOk, error)
	// Old: POST /api/v1/boards/columns/{columnId}/tasks.
	CreateTask(context.Context, *TaskInput) (*BoardTask, error)
	// Old: PUT /api/v1/tasks/{id}.
	UpdateTask(context.Context, *TaskRequest) (*BoardOk, error)
	// Old: DELETE /api/v1/tasks/{id}.
	DeleteTask(context.Context, *BoardIdRequest) (*BoardOk, error)
	// Old: POST /api/v1/tasks/{id}/move.
	MoveTask(context.Context, *MoveTaskRequest) (*BoardOk, error)
	// Old: POST /api/v1/tasks/{id}/trigger.
	TriggerTask(context.Context, *BoardIdRequest) (*BoardTask, error)
	mustEmbedUnimplementedBoardServiceServer()
}

// UnimplementedBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoardServiceServer struct{}

func (UnimplementedBoardServiceServer) List(context.Context, *Empty) (*BoardList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBoardServiceServer) Create(context.Context, *BoardInput) (*Board, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBoardServiceServer) Get(context.Context, *BoardIdRequest) (*BoardDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBoardServiceServer) Update(context.Context, *BoardRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBoardServiceServer) Delete(context.Context, *BoardIdRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBoardServiceServer) CreateColumn(context.Context, *ColumnInput) (*BoardColumn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateColumn not implemented")
}
func (UnimplementedBoardServiceServer) UpdateColumn(context.Context, *ColumnRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateColumn not implemented")
}
func (UnimplementedBoardServiceServer) DeleteColumn(context.Context, *BoardIdRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteColumn not implemented")
}
func (UnimplementedBoardServiceServer) CreateTask(context.Context, *TaskInput) (*BoardTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedBoardServiceServer) UpdateTask(context.Context, *TaskRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedBoardServiceServer) DeleteTask(context.Context, *BoardIdRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedBoardServiceServer) MoveTask(context.Context, *MoveTaskRequest) (*BoardOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveTask not implemented")
}
func (UnimplementedBoardServiceServer) TriggerTask(context.Context, *BoardIdRequest) (*BoardTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerTask not implemented")
}
func (UnimplementedBoardServiceServer) mustEmbedUnimplementedBoardServiceServer() {}
func (UnimplementedBoardServiceServer) testEmbeddedByValue()                      {}

// UnsafeBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoardServiceServer will
// result in compilation errors.
type UnsafeBoardServiceServer interface {
	mustEmbedUnimplementedBoardServiceServer()
}

func RegisterBoardServiceServer(s grpc.ServiceRegistrar, srv BoardServiceServer) {
	// If the following call pancis, it indicates UnimplementedBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoardService_ServiceDesc, srv)
}

func _BoardService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Create(ctx, req.(*BoardInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Get(ctx, req.(*BoardIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Update(ctx, req.(*BoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Delete(ctx, req.(*BoardIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_CreateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).CreateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_CreateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).CreateColumn(ctx, req.(*ColumnInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_UpdateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).UpdateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_UpdateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).UpdateColumn(ctx, req.(*ColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_DeleteColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).DeleteColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_DeleteColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).DeleteColumn(ctx, req.(*BoardIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).CreateTask(ctx, req.(*TaskInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).UpdateTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).DeleteTask(ctx, req.(*BoardIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_MoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).MoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_MoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).MoveTask(ctx, req.(*MoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_TriggerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).TriggerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_TriggerTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).TriggerTask(ctx, req.(*BoardIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoardService_ServiceDesc is the grpc.ServiceDesc for BoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.BoardService",
	HandlerType: (*BoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BoardService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BoardService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BoardService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BoardService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BoardService_Delete_Handler,
		},
		{
			MethodName: "CreateColumn",
			Handler:    _BoardService_CreateColumn_Handler,
		},
		{
			MethodName: "UpdateColumn",
			Handler:    _BoardService_UpdateColumn_Handler,
		},
		{
			MethodName: "DeleteColumn",
			Handler:    _BoardService_DeleteColumn_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _BoardService_CreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _BoardService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _BoardService_DeleteTask_Handler,
		},
		{
			MethodName: "MoveTask",
			Handler:    _BoardService_MoveTask_Handler,
		},
		{
			MethodName: "TriggerTask",
			Handler:    _BoardService_TriggerTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/board.proto",
}
