// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/component.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComponentService_List_FullMethodName          = "/baboflow.v1.ComponentService/List"
	ComponentService_GetSyncStatus_FullMethodName = "/baboflow.v1.ComponentService/GetSyncStatus"
	ComponentService_Sync_FullMethodName          = "/baboflow.v1.ComponentService/Sync"
)

// ComponentServiceClient is the client API for ComponentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComponentServiceClient interface {
	// Old: GET /api/v1/components?category=&keyword=.
	List(ctx context.Context, in *ComponentListRequest, opts ...grpc.CallOption) (*ComponentListResponse, error)
	// Old: GET /api/v1/components/sync.
	GetSyncStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentSyncResult, error)
	// Old: POST /api/v1/components/sync.
	Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentSyncResult, error)
}

type componentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComponentServiceClient(cc grpc.ClientConnInterface) ComponentServiceClient {
	return &componentServiceClient{cc}
}

func (c *componentServiceClient) List(ctx context.Context, in *ComponentListRequest, opts ...grpc.CallOption) (*ComponentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentListResponse)
	err := c.cc.Invoke(ctx, ComponentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) GetSyncStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentSyncResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentSyncResult)
	err := c.cc.Invoke(ctx, ComponentService_GetSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) Sync(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ComponentSyncResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComponentSyncResult)
	err := c.cc.Invoke(ctx, ComponentService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComponentServiceServer is the server API for ComponentService service.
// All implementations must embed UnimplementedComponentServiceServer
// for forward compatibility.
type ComponentServiceServer interface {
	// Old: GET /api/v1/components?category=&keyword=.
	List(context.Context, *ComponentListRequest) (*ComponentListResponse, error)
	// Old: GET /api/v1/components/sync.
	GetSyncStatus(context.Context, *Empty) (*ComponentSyncResult, error)
	// Old: POST /api/v1/components/sync.
	Sync(context.Context, *Empty) (*ComponentSyncResult, error)
	mustEmbedUnimplementedComponentServiceServer()
}

// UnimplementedComponentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComponentServiceServer struct{}

func (UnimplementedComponentServiceServer) List(context.Context, *ComponentListRequest) (*ComponentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedComponentServiceServer) GetSyncStatus(context.Context, *Empty) (*ComponentSyncResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedComponentServiceServer) Sync(context.Context, *Empty) (*ComponentSyncResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedComponentServiceServer) mustEmbedUnimplementedComponentServiceServer() {}
func (UnimplementedComponentServiceServer) testEmbeddedByValue()                          {}

// UnsafeComponentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComponentServiceServer will
// result in compilation errors.
type UnsafeComponentServiceServer interface {
	mustEmbedUnimplementedComponentServiceServer()
}

func RegisterComponentServiceServer(s grpc.ServiceRegistrar, srv ComponentServiceServer) {
	// If the following call pancis, it indicates UnimplementedComponentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComponentService_ServiceDesc, srv)
}

func _ComponentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComponentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).List(ctx, req.(*ComponentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComponentService_GetSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).GetSyncStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComponentService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).Sync(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ComponentService_ServiceDesc is the grpc.ServiceDesc for ComponentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComponentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.ComponentService",
	HandlerType: (*ComponentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ComponentService_List_Handler,
		},
		{
			MethodName: "GetSyncStatus",
			Handler:    _ComponentService_GetSyncStatus_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _ComponentService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/component.proto",
}
