// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/component.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ConfigSchema  *structpb.Struct       `protobuf:"bytes,5,opt,name=configSchema,proto3" json:"configSchema,omitempty"`
	Example       *structpb.Struct       `protobuf:"bytes,6,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentMeta) Reset() {
	*x = ComponentMeta{}
	mi := &file_baboflow_v1_component_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMeta) ProtoMessage() {}

func (x *ComponentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_component_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMeta.ProtoReflect.Descriptor instead.
func (*ComponentMeta) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_component_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComponentMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentMeta) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ComponentMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ComponentMeta) GetConfigSchema() *structpb.Struct {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *ComponentMeta) GetExample() *structpb.Struct {
	if x != nil {
		return x.Example
	}
	return nil
}

type ComponentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentListRequest) Reset() {
	*x = ComponentListRequest{}
	mi := &file_baboflow_v1_component_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentListRequest) ProtoMessage() {}

func (x *ComponentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_component_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentListRequest.ProtoReflect.Descriptor instead.
func (*ComponentListRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_component_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentListRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ComponentListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ComponentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ComponentMeta       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentListResponse) Reset() {
	*x = ComponentListResponse{}
	mi := &file_baboflow_v1_component_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentListResponse) ProtoMessage() {}

func (x *ComponentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_component_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentListResponse.ProtoReflect.Descriptor instead.
func (*ComponentListResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_component_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentListResponse) GetList() []*ComponentMeta {
	if x != nil {
		return x.List
	}
	return nil
}

type ComponentSyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed       int32                  `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	Skipped       int32                  `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	LastRunAt     string                 `protobuf:"bytes,5,opt,name=lastRunAt,proto3" json:"lastRunAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentSyncResult) Reset() {
	*x = ComponentSyncResult{}
	mi := &file_baboflow_v1_component_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentSyncResult) ProtoMessage() {}

func (x *ComponentSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_component_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentSyncResult.ProtoReflect.Descriptor instead.
func (*ComponentSyncResult) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_component_proto_rawDescGZIP(), []int{3}
}

func (x *ComponentSyncResult) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ComponentSyncResult) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *ComponentSyncResult) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *ComponentSyncResult) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ComponentSyncResult) GetLastRunAt() string {
	if x != nil {
		return x.LastRunAt
	}
	return ""
}

var File_baboflow_v1_component_proto protoreflect.FileDescriptor

const file_baboflow_v1_component_proto_rawDesc = "" +
	"\n" +
	"\x1bbaboflow/v1/component.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18baboflow/v1/common.proto\"\xe5\x01\n" +
	"\rComponentMeta\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12;\n" +
	"\fconfigSchema\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fconfigSchema\x121\n" +
	"\aexample\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aexample\"L\n" +
	"\x14ComponentListRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"G\n" +
	"\x15ComponentListResponse\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.baboflow.v1.ComponentMetaR\x04list\"\x97\x01\n" +
	"\x13ComponentSyncResult\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\x05R\aremoved\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x1c\n" +
	"\tlastRunAt\x18\x05 \x01(\tR\tlastRunAt2\xc7\x02\n" +
	"\x10ComponentService\x12i\n" +
	"\x04List\x12!.baboflow.v1.ComponentListRequest\x1a\".baboflow.v1.ComponentListResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/components\x12f\n" +
	"\rGetSyncStatus\x12\x12.baboflow.v1.Empty\x1a .baboflow.v1.ComponentSyncResult\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/components/sync\x12`\n" +
	"\x04Sync\x12\x12.baboflow.v1.Empty\x1a .baboflow.v1.ComponentSyncResult\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/components/syncB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_component_proto_rawDescOnce sync.Once
	file_baboflow_v1_component_proto_rawDescData []byte
)

func file_baboflow_v1_component_proto_rawDescGZIP() []byte {
	file_baboflow_v1_component_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_component_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_component_proto_rawDesc), len(file_baboflow_v1_component_proto_rawDesc)))
	})
	return file_baboflow_v1_component_proto_rawDescData
}

var file_baboflow_v1_component_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_baboflow_v1_component_proto_goTypes = []any{
	(*ComponentMeta)(nil),         // 0: baboflow.v1.ComponentMeta
	(*ComponentListRequest)(nil),  // 1: baboflow.v1.ComponentListRequest
	(*ComponentListResponse)(nil), // 2: baboflow.v1.ComponentListResponse
	(*ComponentSyncResult)(nil),   // 3: baboflow.v1.ComponentSyncResult
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*Empty)(nil),                 // 5: baboflow.v1.Empty
}
var file_baboflow_v1_component_proto_depIdxs = []int32{
	4, // 0: baboflow.v1.ComponentMeta.configSchema:type_name -> google.protobuf.Struct
	4, // 1: baboflow.v1.ComponentMeta.example:type_name -> google.protobuf.Struct
	0, // 2: baboflow.v1.ComponentListResponse.list:type_name -> baboflow.v1.ComponentMeta
	1, // 3: baboflow.v1.ComponentService.List:input_type -> baboflow.v1.ComponentListRequest
	5, // 4: baboflow.v1.ComponentService.GetSyncStatus:input_type -> baboflow.v1.Empty
	5, // 5: baboflow.v1.ComponentService.Sync:input_type -> baboflow.v1.Empty
	2, // 6: baboflow.v1.ComponentService.List:output_type -> baboflow.v1.ComponentListResponse
	3, // 7: baboflow.v1.ComponentService.GetSyncStatus:output_type -> baboflow.v1.ComponentSyncResult
	3, // 8: baboflow.v1.ComponentService.Sync:output_type -> baboflow.v1.ComponentSyncResult
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_baboflow_v1_component_proto_init() }
func file_baboflow_v1_component_proto_init() {
	if File_baboflow_v1_component_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_component_proto_rawDesc), len(file_baboflow_v1_component_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_component_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_component_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_component_proto_msgTypes,
	}.Build()
	File_baboflow_v1_component_proto = out.File
	file_baboflow_v1_component_proto_goTypes = nil
	file_baboflow_v1_component_proto_depIdxs = nil
}
