// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/component.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationComponentServiceGetSyncStatus = "/baboflow.v1.ComponentService/GetSyncStatus"
const OperationComponentServiceList = "/baboflow.v1.ComponentService/List"
const OperationComponentServiceSync = "/baboflow.v1.ComponentService/Sync"

type ComponentServiceHTTPServer interface {
	// GetSyncStatus Old: GET /api/v1/components/sync.
	GetSyncStatus(context.Context, *Empty) (*ComponentSyncResult, error)
	// List Old: GET /api/v1/components?category=&keyword=.
	List(context.Context, *ComponentListRequest) (*ComponentListResponse, error)
	// Sync Old: POST /api/v1/components/sync.
	Sync(context.Context, *Empty) (*ComponentSyncResult, error)
}

func RegisterComponentServiceHTTPServer(s *http.Server, srv ComponentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/components", _ComponentService_List0_HTTP_Handler(srv))
	r.GET("/api/v1/components/sync", _ComponentService_GetSyncStatus0_HTTP_Handler(srv))
	r.POST("/api/v1/components/sync", _ComponentService_Sync0_HTTP_Handler(srv))
}

func _ComponentService_List0_HTTP_Handler(srv ComponentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ComponentListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ComponentListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ComponentListResponse)
		return ctx.Result(200, reply)
	}
}

func _ComponentService_GetSyncStatus0_HTTP_Handler(srv ComponentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentServiceGetSyncStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSyncStatus(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ComponentSyncResult)
		return ctx.Result(200, reply)
	}
}

func _ComponentService_Sync0_HTTP_Handler(srv ComponentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationComponentServiceSync)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Sync(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ComponentSyncResult)
		return ctx.Result(200, reply)
	}
}

type ComponentServiceHTTPClient interface {
	// GetSyncStatus Old: GET /api/v1/components/sync.
	GetSyncStatus(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ComponentSyncResult, err error)
	// List Old: GET /api/v1/components?category=&keyword=.
	List(ctx context.Context, req *ComponentListRequest, opts ...http.CallOption) (rsp *ComponentListResponse, err error)
	// Sync Old: POST /api/v1/components/sync.
	Sync(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ComponentSyncResult, err error)
}

type ComponentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewComponentServiceHTTPClient(client *http.Client) ComponentServiceHTTPClient {
	return &ComponentServiceHTTPClientImpl{client}
}

// GetSyncStatus Old: GET /api/v1/components/sync.
func (c *ComponentServiceHTTPClientImpl) GetSyncStatus(ctx context.Context, in *Empty, opts ...http.CallOption) (*ComponentSyncResult, error) {
	var out ComponentSyncResult
	pattern := "/api/v1/components/sync"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationComponentServiceGetSyncStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List Old: GET /api/v1/components?category=&keyword=.
func (c *ComponentServiceHTTPClientImpl) List(ctx context.Context, in *ComponentListRequest, opts ...http.CallOption) (*ComponentListResponse, error) {
	var out ComponentListResponse
	pattern := "/api/v1/components"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationComponentServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Sync Old: POST /api/v1/components/sync.
func (c *ComponentServiceHTTPClientImpl) Sync(ctx context.Context, in *Empty, opts ...http.CallOption) (*ComponentSyncResult, error) {
	var out ComponentSyncResult
	pattern := "/api/v1/components/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationComponentServiceSync))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
