// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/cron.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CronJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,5,opt,name=scheduleType,proto3" json:"scheduleType,omitempty"`
	CronExpr      string                 `protobuf:"bytes,6,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	IntervalSec   int64                  `protobuf:"varint,7,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	RunAt         string                 `protobuf:"bytes,8,opt,name=runAt,proto3" json:"runAt,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastRunAt     string                 `protobuf:"bytes,11,opt,name=lastRunAt,proto3" json:"lastRunAt,omitempty"`
	LastStatus    string                 `protobuf:"bytes,12,opt,name=lastStatus,proto3" json:"lastStatus,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronJob) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CronJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJob) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CronJob) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CronJob) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *CronJob) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CronJob) GetIntervalSec() int64 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *CronJob) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

func (x *CronJob) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CronJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CronJob) GetLastRunAt() string {
	if x != nil {
		return x.LastRunAt
	}
	return ""
}

func (x *CronJob) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *CronJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CronJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CronInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,4,opt,name=scheduleType,proto3" json:"scheduleType,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	IntervalSec   int64                  `protobuf:"varint,6,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	RunAt         string                 `protobuf:"bytes,7,opt,name=runAt,proto3" json:"runAt,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronInput) Reset() {
	*x = CronInput{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronInput) ProtoMessage() {}

func (x *CronInput) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronInput.ProtoReflect.Descriptor instead.
func (*CronInput) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *CronInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronInput) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CronInput) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CronInput) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *CronInput) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CronInput) GetIntervalSec() int64 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *CronInput) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

func (x *CronInput) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=targetType,proto3" json:"targetType,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,5,opt,name=scheduleType,proto3" json:"scheduleType,omitempty"`
	CronExpr      string                 `protobuf:"bytes,6,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	IntervalSec   int64                  `protobuf:"varint,7,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	RunAt         string                 `protobuf:"bytes,8,opt,name=runAt,proto3" json:"runAt,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJobRequest) Reset() {
	*x = CronJobRequest{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJobRequest) ProtoMessage() {}

func (x *CronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJobRequest.ProtoReflect.Descriptor instead.
func (*CronJobRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *CronJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CronJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJobRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CronJobRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CronJobRequest) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *CronJobRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CronJobRequest) GetIntervalSec() int64 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *CronJobRequest) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

func (x *CronJobRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CronJobIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJobIdRequest) Reset() {
	*x = CronJobIdRequest{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJobIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJobIdRequest) ProtoMessage() {}

func (x *CronJobIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJobIdRequest.ProtoReflect.Descriptor instead.
func (*CronJobIdRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *CronJobIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CronJobList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CronJob             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJobList) Reset() {
	*x = CronJobList{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJobList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJobList) ProtoMessage() {}

func (x *CronJobList) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJobList.ProtoReflect.Descriptor instead.
func (*CronJobList) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *CronJobList) GetList() []*CronJob {
	if x != nil {
		return x.List
	}
	return nil
}

type CronOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronOk) Reset() {
	*x = CronOk{}
	mi := &file_baboflow_v1_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronOk) ProtoMessage() {}

func (x *CronOk) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronOk.ProtoReflect.Descriptor instead.
func (*CronOk) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_cron_proto_rawDescGZIP(), []int{5}
}

func (x *CronOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_baboflow_v1_cron_proto protoreflect.FileDescriptor

const file_baboflow_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x16baboflow/v1/cron.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18baboflow/v1/common.proto\"\xa8\x03\n" +
	"\aCronJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"targetType\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x04 \x01(\tR\btargetId\x12\"\n" +
	"\fscheduleType\x18\x05 \x01(\tR\fscheduleType\x12\x1a\n" +
	"\bcronExpr\x18\x06 \x01(\tR\bcronExpr\x12 \n" +
	"\vintervalSec\x18\a \x01(\x03R\vintervalSec\x12\x14\n" +
	"\x05runAt\x18\b \x01(\tR\x05runAt\x121\n" +
	"\apayload\x18\t \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x1c\n" +
	"\tlastRunAt\x18\v \x01(\tR\tlastRunAt\x12\x1e\n" +
	"\n" +
	"lastStatus\x18\f \x01(\tR\n" +
	"lastStatus\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\tR\tupdatedAt\"\x86\x02\n" +
	"\tCronInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"targetType\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\x12\"\n" +
	"\fscheduleType\x18\x04 \x01(\tR\fscheduleType\x12\x1a\n" +
	"\bcronExpr\x18\x05 \x01(\tR\bcronExpr\x12 \n" +
	"\vintervalSec\x18\x06 \x01(\x03R\vintervalSec\x12\x14\n" +
	"\x05runAt\x18\a \x01(\tR\x05runAt\x121\n" +
	"\apayload\x18\b \x01(\v2\x17.google.protobuf.StructR\apayload\"\x9b\x02\n" +
	"\x0eCronJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"targetType\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1a\n" +
	"\btargetId\x18\x04 \x01(\tR\btargetId\x12\"\n" +
	"\fscheduleType\x18\x05 \x01(\tR\fscheduleType\x12\x1a\n" +
	"\bcronExpr\x18\x06 \x01(\tR\bcronExpr\x12 \n" +
	"\vintervalSec\x18\a \x01(\x03R\vintervalSec\x12\x14\n" +
	"\x05runAt\x18\b \x01(\tR\x05runAt\x121\n" +
	"\apayload\x18\t \x01(\v2\x17.google.protobuf.StructR\apayload\"\"\n" +
	"\x10CronJobIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\vCronJobList\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.baboflow.v1.CronJobR\x04list\"\x18\n" +
	"\x06CronOk\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xda\x03\n" +
	"\vCronService\x12O\n" +
	"\x04List\x12\x12.baboflow.v1.Empty\x1a\x18.baboflow.v1.CronJobList\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/cron-jobs\x12T\n" +
	"\x06Create\x12\x16.baboflow.v1.CronInput\x1a\x14.baboflow.v1.CronJob\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/cron-jobs\x12]\n" +
	"\x06Update\x12\x1b.baboflow.v1.CronJobRequest\x1a\x13.baboflow.v1.CronOk\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/cron-jobs/{id}\x12\\\n" +
	"\x06Delete\x12\x1d.baboflow.v1.CronJobIdRequest\x1a\x13.baboflow.v1.CronOk\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/cron-jobs/{id}\x12g\n" +
	"\x06Toggle\x12\x1d.baboflow.v1.CronJobIdRequest\x1a\x14.baboflow.v1.CronJob\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/cron-jobs/{id}/toggleB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_cron_proto_rawDescOnce sync.Once
	file_baboflow_v1_cron_proto_rawDescData []byte
)

func file_baboflow_v1_cron_proto_rawDescGZIP() []byte {
	file_baboflow_v1_cron_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_cron_proto_rawDesc), len(file_baboflow_v1_cron_proto_rawDesc)))
	})
	return file_baboflow_v1_cron_proto_rawDescData
}

var file_baboflow_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_baboflow_v1_cron_proto_goTypes = []any{
	(*CronJob)(nil),          // 0: baboflow.v1.CronJob
	(*CronInput)(nil),        // 1: baboflow.v1.CronInput
	(*CronJobRequest)(nil),   // 2: baboflow.v1.CronJobRequest
	(*CronJobIdRequest)(nil), // 3: baboflow.v1.CronJobIdRequest
	(*CronJobList)(nil),      // 4: baboflow.v1.CronJobList
	(*CronOk)(nil),           // 5: baboflow.v1.CronOk
	(*structpb.Struct)(nil),  // 6: google.protobuf.Struct
	(*Empty)(nil),            // 7: baboflow.v1.Empty
}
var file_baboflow_v1_cron_proto_depIdxs = []int32{
	6, // 0: baboflow.v1.CronJob.payload:type_name -> google.protobuf.Struct
	6, // 1: baboflow.v1.CronInput.payload:type_name -> google.protobuf.Struct
	6, // 2: baboflow.v1.CronJobRequest.payload:type_name -> google.protobuf.Struct
	0, // 3: baboflow.v1.CronJobList.list:type_name -> baboflow.v1.CronJob
	7, // 4: baboflow.v1.CronService.List:input_type -> baboflow.v1.Empty
	1, // 5: baboflow.v1.CronService.Create:input_type -> baboflow.v1.CronInput
	2, // 6: baboflow.v1.CronService.Update:input_type -> baboflow.v1.CronJobRequest
	3, // 7: baboflow.v1.CronService.Delete:input_type -> baboflow.v1.CronJobIdRequest
	3, // 8: baboflow.v1.CronService.Toggle:input_type -> baboflow.v1.CronJobIdRequest
	4, // 9: baboflow.v1.CronService.List:output_type -> baboflow.v1.CronJobList
	0, // 10: baboflow.v1.CronService.Create:output_type -> baboflow.v1.CronJob
	5, // 11: baboflow.v1.CronService.Update:output_type -> baboflow.v1.CronOk
	5, // 12: baboflow.v1.CronService.Delete:output_type -> baboflow.v1.CronOk
	0, // 13: baboflow.v1.CronService.Toggle:output_type -> baboflow.v1.CronJob
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baboflow_v1_cron_proto_init() }
func file_baboflow_v1_cron_proto_init() {
	if File_baboflow_v1_cron_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_cron_proto_rawDesc), len(file_baboflow_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_cron_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_cron_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_cron_proto_msgTypes,
	}.Build()
	File_baboflow_v1_cron_proto = out.File
	file_baboflow_v1_cron_proto_goTypes = nil
	file_baboflow_v1_cron_proto_depIdxs = nil
}
