// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/llm.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLLMServiceCreateModels = "/baboflow.v1.LLMService/CreateModels"
const OperationLLMServiceCreateProvider = "/baboflow.v1.LLMService/CreateProvider"
const OperationLLMServiceDeleteModel = "/baboflow.v1.LLMService/DeleteModel"
const OperationLLMServiceDeleteProvider = "/baboflow.v1.LLMService/DeleteProvider"
const OperationLLMServiceListModels = "/baboflow.v1.LLMService/ListModels"
const OperationLLMServiceListProviders = "/baboflow.v1.LLMService/ListProviders"
const OperationLLMServiceListRemoteModels = "/baboflow.v1.LLMService/ListRemoteModels"
const OperationLLMServiceSetDefaultModel = "/baboflow.v1.LLMService/SetDefaultModel"
const OperationLLMServiceTestModel = "/baboflow.v1.LLMService/TestModel"
const OperationLLMServiceTestProvider = "/baboflow.v1.LLMService/TestProvider"
const OperationLLMServiceUpdateModel = "/baboflow.v1.LLMService/UpdateModel"
const OperationLLMServiceUpdateProvider = "/baboflow.v1.LLMService/UpdateProvider"

type LLMServiceHTTPServer interface {
	// CreateModels Old: POST /api/v1/llm/providers/{id}/models.
	CreateModels(context.Context, *CreateModelsRequest) (*OkResponse, error)
	// CreateProvider Old: POST /api/v1/llm/providers.
	CreateProvider(context.Context, *ProviderInput) (*CreateIdResponse, error)
	// DeleteModel Old: DELETE /api/v1/llm/models/{modelId}.
	DeleteModel(context.Context, *ModelIdRequest) (*OkResponse, error)
	// DeleteProvider Old: DELETE /api/v1/llm/providers/{id}.
	DeleteProvider(context.Context, *IdRequest) (*OkResponse, error)
	// ListModels Old: GET /api/v1/llm/providers/{id}/models.
	ListModels(context.Context, *ProviderModelsRequest) (*ModelList, error)
	// ListProviders Old: GET /api/v1/llm/providers.
	ListProviders(context.Context, *Empty) (*ProviderList, error)
	// ListRemoteModels Old: GET /api/v1/llm/providers/{id}/models/remote.
	ListRemoteModels(context.Context, *IdRequest) (*StringList, error)
	// SetDefaultModel Old: POST /api/v1/llm/models/{modelId}/default.
	SetDefaultModel(context.Context, *ModelIdRequest) (*OkResponse, error)
	// TestModel Old: POST /api/v1/llm/models/{modelId}/test.
	TestModel(context.Context, *ModelIdRequest) (*TestResult, error)
	// TestProvider Old: POST /api/v1/llm/providers/{id}/test.
	TestProvider(context.Context, *IdRequest) (*TestResult, error)
	// UpdateModel Old: PUT /api/v1/llm/models/{modelId}.
	UpdateModel(context.Context, *UpdateModelRequest) (*OkResponse, error)
	// UpdateProvider Old: PUT /api/v1/llm/providers/{id}.
	UpdateProvider(context.Context, *UpdateProviderRequest) (*OkResponse, error)
}

func RegisterLLMServiceHTTPServer(s *http.Server, srv LLMServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/llm/providers", _LLMService_ListProviders0_HTTP_Handler(srv))
	r.POST("/api/v1/llm/providers", _LLMService_CreateProvider0_HTTP_Handler(srv))
	r.PUT("/api/v1/llm/providers/{id}", _LLMService_UpdateProvider0_HTTP_Handler(srv))
	r.DELETE("/api/v1/llm/providers/{id}", _LLMService_DeleteProvider0_HTTP_Handler(srv))
	r.POST("/api/v1/llm/providers/{id}/test", _LLMService_TestProvider0_HTTP_Handler(srv))
	r.GET("/api/v1/llm/providers/{id}/models/remote", _LLMService_ListRemoteModels0_HTTP_Handler(srv))
	r.GET("/api/v1/llm/providers/{providerId}/models", _LLMService_ListModels0_HTTP_Handler(srv))
	r.POST("/api/v1/llm/providers/{providerId}/models", _LLMService_CreateModels0_HTTP_Handler(srv))
	r.PUT("/api/v1/llm/models/{modelId}", _LLMService_UpdateModel0_HTTP_Handler(srv))
	r.DELETE("/api/v1/llm/models/{modelId}", _LLMService_DeleteModel0_HTTP_Handler(srv))
	r.POST("/api/v1/llm/models/{modelId}/default", _LLMService_SetDefaultModel0_HTTP_Handler(srv))
	r.POST("/api/v1/llm/models/{modelId}/test", _LLMService_TestModel0_HTTP_Handler(srv))
}

func _LLMService_ListProviders0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceListProviders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProviders(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProviderList)
		return ctx.Result(200, reply)
	}
}

func _LLMService_CreateProvider0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProviderInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceCreateProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProvider(ctx, req.(*ProviderInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateIdResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_UpdateProvider0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProviderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceUpdateProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProvider(ctx, req.(*UpdateProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_DeleteProvider0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceDeleteProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProvider(ctx, req.(*IdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_TestProvider0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceTestProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestProvider(ctx, req.(*IdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TestResult)
		return ctx.Result(200, reply)
	}
}

func _LLMService_ListRemoteModels0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceListRemoteModels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRemoteModels(ctx, req.(*IdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StringList)
		return ctx.Result(200, reply)
	}
}

func _LLMService_ListModels0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProviderModelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceListModels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModels(ctx, req.(*ProviderModelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ModelList)
		return ctx.Result(200, reply)
	}
}

func _LLMService_CreateModels0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateModelsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceCreateModels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateModels(ctx, req.(*CreateModelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_UpdateModel0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateModelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceUpdateModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateModel(ctx, req.(*UpdateModelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_DeleteModel0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ModelIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceDeleteModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteModel(ctx, req.(*ModelIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_SetDefaultModel0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ModelIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceSetDefaultModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDefaultModel(ctx, req.(*ModelIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OkResponse)
		return ctx.Result(200, reply)
	}
}

func _LLMService_TestModel0_HTTP_Handler(srv LLMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ModelIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLLMServiceTestModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestModel(ctx, req.(*ModelIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TestResult)
		return ctx.Result(200, reply)
	}
}

type LLMServiceHTTPClient interface {
	// CreateModels Old: POST /api/v1/llm/providers/{id}/models.
	CreateModels(ctx context.Context, req *CreateModelsRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
	// CreateProvider Old: POST /api/v1/llm/providers.
	CreateProvider(ctx context.Context, req *ProviderInput, opts ...http.CallOption) (rsp *CreateIdResponse, err error)
	// DeleteModel Old: DELETE /api/v1/llm/models/{modelId}.
	DeleteModel(ctx context.Context, req *ModelIdRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
	// DeleteProvider Old: DELETE /api/v1/llm/providers/{id}.
	DeleteProvider(ctx context.Context, req *IdRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
	// ListModels Old: GET /api/v1/llm/providers/{id}/models.
	ListModels(ctx context.Context, req *ProviderModelsRequest, opts ...http.CallOption) (rsp *ModelList, err error)
	// ListProviders Old: GET /api/v1/llm/providers.
	ListProviders(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ProviderList, err error)
	// ListRemoteModels Old: GET /api/v1/llm/providers/{id}/models/remote.
	ListRemoteModels(ctx context.Context, req *IdRequest, opts ...http.CallOption) (rsp *StringList, err error)
	// SetDefaultModel Old: POST /api/v1/llm/models/{modelId}/default.
	SetDefaultModel(ctx context.Context, req *ModelIdRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
	// TestModel Old: POST /api/v1/llm/models/{modelId}/test.
	TestModel(ctx context.Context, req *ModelIdRequest, opts ...http.CallOption) (rsp *TestResult, err error)
	// TestProvider Old: POST /api/v1/llm/providers/{id}/test.
	TestProvider(ctx context.Context, req *IdRequest, opts ...http.CallOption) (rsp *TestResult, err error)
	// UpdateModel Old: PUT /api/v1/llm/models/{modelId}.
	UpdateModel(ctx context.Context, req *UpdateModelRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
	// UpdateProvider Old: PUT /api/v1/llm/providers/{id}.
	UpdateProvider(ctx context.Context, req *UpdateProviderRequest, opts ...http.CallOption) (rsp *OkResponse, err error)
}

type LLMServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLLMServiceHTTPClient(client *http.Client) LLMServiceHTTPClient {
	return &LLMServiceHTTPClientImpl{client}
}

// CreateModels Old: POST /api/v1/llm/providers/{id}/models.
func (c *LLMServiceHTTPClientImpl) CreateModels(ctx context.Context, in *CreateModelsRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/providers/{providerId}/models"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceCreateModels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateProvider Old: POST /api/v1/llm/providers.
func (c *LLMServiceHTTPClientImpl) CreateProvider(ctx context.Context, in *ProviderInput, opts ...http.CallOption) (*CreateIdResponse, error) {
	var out CreateIdResponse
	pattern := "/api/v1/llm/providers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceCreateProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteModel Old: DELETE /api/v1/llm/models/{modelId}.
func (c *LLMServiceHTTPClientImpl) DeleteModel(ctx context.Context, in *ModelIdRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/models/{modelId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLLMServiceDeleteModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteProvider Old: DELETE /api/v1/llm/providers/{id}.
func (c *LLMServiceHTTPClientImpl) DeleteProvider(ctx context.Context, in *IdRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/providers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLLMServiceDeleteProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListModels Old: GET /api/v1/llm/providers/{id}/models.
func (c *LLMServiceHTTPClientImpl) ListModels(ctx context.Context, in *ProviderModelsRequest, opts ...http.CallOption) (*ModelList, error) {
	var out ModelList
	pattern := "/api/v1/llm/providers/{providerId}/models"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLLMServiceListModels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProviders Old: GET /api/v1/llm/providers.
func (c *LLMServiceHTTPClientImpl) ListProviders(ctx context.Context, in *Empty, opts ...http.CallOption) (*ProviderList, error) {
	var out ProviderList
	pattern := "/api/v1/llm/providers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLLMServiceListProviders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRemoteModels Old: GET /api/v1/llm/providers/{id}/models/remote.
func (c *LLMServiceHTTPClientImpl) ListRemoteModels(ctx context.Context, in *IdRequest, opts ...http.CallOption) (*StringList, error) {
	var out StringList
	pattern := "/api/v1/llm/providers/{id}/models/remote"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLLMServiceListRemoteModels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetDefaultModel Old: POST /api/v1/llm/models/{modelId}/default.
func (c *LLMServiceHTTPClientImpl) SetDefaultModel(ctx context.Context, in *ModelIdRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/models/{modelId}/default"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceSetDefaultModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestModel Old: POST /api/v1/llm/models/{modelId}/test.
func (c *LLMServiceHTTPClientImpl) TestModel(ctx context.Context, in *ModelIdRequest, opts ...http.CallOption) (*TestResult, error) {
	var out TestResult
	pattern := "/api/v1/llm/models/{modelId}/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceTestModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestProvider Old: POST /api/v1/llm/providers/{id}/test.
func (c *LLMServiceHTTPClientImpl) TestProvider(ctx context.Context, in *IdRequest, opts ...http.CallOption) (*TestResult, error) {
	var out TestResult
	pattern := "/api/v1/llm/providers/{id}/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceTestProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateModel Old: PUT /api/v1/llm/models/{modelId}.
func (c *LLMServiceHTTPClientImpl) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/models/{modelId}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceUpdateModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateProvider Old: PUT /api/v1/llm/providers/{id}.
func (c *LLMServiceHTTPClientImpl) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...http.CallOption) (*OkResponse, error) {
	var out OkResponse
	pattern := "/api/v1/llm/providers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLLMServiceUpdateProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
