// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/llm.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMService_ListProviders_FullMethodName    = "/baboflow.v1.LLMService/ListProviders"
	LLMService_CreateProvider_FullMethodName   = "/baboflow.v1.LLMService/CreateProvider"
	LLMService_UpdateProvider_FullMethodName   = "/baboflow.v1.LLMService/UpdateProvider"
	LLMService_DeleteProvider_FullMethodName   = "/baboflow.v1.LLMService/DeleteProvider"
	LLMService_TestProvider_FullMethodName     = "/baboflow.v1.LLMService/TestProvider"
	LLMService_ListRemoteModels_FullMethodName = "/baboflow.v1.LLMService/ListRemoteModels"
	LLMService_ListModels_FullMethodName       = "/baboflow.v1.LLMService/ListModels"
	LLMService_CreateModels_FullMethodName     = "/baboflow.v1.LLMService/CreateModels"
	LLMService_UpdateModel_FullMethodName      = "/baboflow.v1.LLMService/UpdateModel"
	LLMService_DeleteModel_FullMethodName      = "/baboflow.v1.LLMService/DeleteModel"
	LLMService_SetDefaultModel_FullMethodName  = "/baboflow.v1.LLMService/SetDefaultModel"
	LLMService_TestModel_FullMethodName        = "/baboflow.v1.LLMService/TestModel"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	// Old: GET /api/v1/llm/providers.
	ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error)
	// Old: POST /api/v1/llm/providers.
	CreateProvider(ctx context.Context, in *ProviderInput, opts ...grpc.CallOption) (*CreateIdResponse, error)
	// Old: PUT /api/v1/llm/providers/{id}.
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: DELETE /api/v1/llm/providers/{id}.
	DeleteProvider(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: POST /api/v1/llm/providers/{id}/test.
	TestProvider(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TestResult, error)
	// Old: GET /api/v1/llm/providers/{id}/models/remote.
	ListRemoteModels(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StringList, error)
	// Old: GET /api/v1/llm/providers/{id}/models.
	ListModels(ctx context.Context, in *ProviderModelsRequest, opts ...grpc.CallOption) (*ModelList, error)
	// Old: POST /api/v1/llm/providers/{id}/models.
	CreateModels(ctx context.Context, in *CreateModelsRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: PUT /api/v1/llm/models/{modelId}.
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: DELETE /api/v1/llm/models/{modelId}.
	DeleteModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: POST /api/v1/llm/models/{modelId}/default.
	SetDefaultModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*OkResponse, error)
	// Old: POST /api/v1/llm/models/{modelId}/test.
	TestModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*TestResult, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderList)
	err := c.cc.Invoke(ctx, LLMService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateProvider(ctx context.Context, in *ProviderInput, opts ...grpc.CallOption) (*CreateIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIdResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteProvider(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TestProvider(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResult)
	err := c.cc.Invoke(ctx, LLMService_TestProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListRemoteModels(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*StringList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringList)
	err := c.cc.Invoke(ctx, LLMService_ListRemoteModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListModels(ctx context.Context, in *ProviderModelsRequest, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, LLMService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateModels(ctx context.Context, in *CreateModelsRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) SetDefaultModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*OkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkResponse)
	err := c.cc.Invoke(ctx, LLMService_SetDefaultModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TestModel(ctx context.Context, in *ModelIdRequest, opts ...grpc.CallOption) (*TestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResult)
	err := c.cc.Invoke(ctx, LLMService_TestModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility.
type LLMServiceServer interface {
	// Old: GET /api/v1/llm/providers.
	ListProviders(context.Context, *Empty) (*ProviderList, error)
	// Old: POST /api/v1/llm/providers.
	CreateProvider(context.Context, *ProviderInput) (*CreateIdResponse, error)
	// Old: PUT /api/v1/llm/providers/{id}.
	UpdateProvider(context.Context, *UpdateProviderRequest) (*OkResponse, error)
	// Old: DELETE /api/v1/llm/providers/{id}.
	DeleteProvider(context.Context, *IdRequest) (*OkResponse, error)
	// Old: POST /api/v1/llm/providers/{id}/test.
	TestProvider(context.Context, *IdRequest) (*TestResult, error)
	// Old: GET /api/v1/llm/providers/{id}/models/remote.
	ListRemoteModels(context.Context, *IdRequest) (*StringList, error)
	// Old: GET /api/v1/llm/providers/{id}/models.
	ListModels(context.Context, *ProviderModelsRequest) (*ModelList, error)
	// Old: POST /api/v1/llm/providers/{id}/models.
	CreateModels(context.Context, *CreateModelsRequest) (*OkResponse, error)
	// Old: PUT /api/v1/llm/models/{modelId}.
	UpdateModel(context.Context, *UpdateModelRequest) (*OkResponse, error)
	// Old: DELETE /api/v1/llm/models/{modelId}.
	DeleteModel(context.Context, *ModelIdRequest) (*OkResponse, error)
	// Old: POST /api/v1/llm/models/{modelId}/default.
	SetDefaultModel(context.Context, *ModelIdRequest) (*OkResponse, error)
	// Old: POST /api/v1/llm/models/{modelId}/test.
	TestModel(context.Context, *ModelIdRequest) (*TestResult, error)
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) ListProviders(context.Context, *Empty) (*ProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedLLMServiceServer) CreateProvider(context.Context, *ProviderInput) (*CreateIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedLLMServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedLLMServiceServer) DeleteProvider(context.Context, *IdRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedLLMServiceServer) TestProvider(context.Context, *IdRequest) (*TestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestProvider not implemented")
}
func (UnimplementedLLMServiceServer) ListRemoteModels(context.Context, *IdRequest) (*StringList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRemoteModels not implemented")
}
func (UnimplementedLLMServiceServer) ListModels(context.Context, *ProviderModelsRequest) (*ModelList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLLMServiceServer) CreateModels(context.Context, *CreateModelsRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModels not implemented")
}
func (UnimplementedLLMServiceServer) UpdateModel(context.Context, *UpdateModelRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedLLMServiceServer) DeleteModel(context.Context, *ModelIdRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedLLMServiceServer) SetDefaultModel(context.Context, *ModelIdRequest) (*OkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultModel not implemented")
}
func (UnimplementedLLMServiceServer) TestModel(context.Context, *ModelIdRequest) (*TestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestModel not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}
func (UnimplementedLLMServiceServer) testEmbeddedByValue()                    {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call pancis, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateProvider(ctx, req.(*ProviderInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteProvider(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TestProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TestProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TestProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TestProvider(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListRemoteModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListRemoteModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListRemoteModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListRemoteModels(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListModels(ctx, req.(*ProviderModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateModels(ctx, req.(*CreateModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteModel(ctx, req.(*ModelIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_SetDefaultModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).SetDefaultModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_SetDefaultModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).SetDefaultModel(ctx, req.(*ModelIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TestModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TestModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TestModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TestModel(ctx, req.(*ModelIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _LLMService_ListProviders_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _LLMService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _LLMService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _LLMService_DeleteProvider_Handler,
		},
		{
			MethodName: "TestProvider",
			Handler:    _LLMService_TestProvider_Handler,
		},
		{
			MethodName: "ListRemoteModels",
			Handler:    _LLMService_ListRemoteModels_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LLMService_ListModels_Handler,
		},
		{
			MethodName: "CreateModels",
			Handler:    _LLMService_CreateModels_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _LLMService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _LLMService_DeleteModel_Handler,
		},
		{
			MethodName: "SetDefaultModel",
			Handler:    _LLMService_SetDefaultModel_Handler,
		},
		{
			MethodName: "TestModel",
			Handler:    _LLMService_TestModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/llm.proto",
}
