// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/mcp.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	McpService_ListServers_FullMethodName    = "/baboflow.v1.McpService/ListServers"
	McpService_CreateServer_FullMethodName   = "/baboflow.v1.McpService/CreateServer"
	McpService_UpdateServer_FullMethodName   = "/baboflow.v1.McpService/UpdateServer"
	McpService_DeleteServer_FullMethodName   = "/baboflow.v1.McpService/DeleteServer"
	McpService_ToggleServer_FullMethodName   = "/baboflow.v1.McpService/ToggleServer"
	McpService_TestServer_FullMethodName     = "/baboflow.v1.McpService/TestServer"
	McpService_ListExposures_FullMethodName  = "/baboflow.v1.McpService/ListExposures"
	McpService_Expose_FullMethodName         = "/baboflow.v1.McpService/Expose"
	McpService_RemoveExposure_FullMethodName = "/baboflow.v1.McpService/RemoveExposure"
)

// McpServiceClient is the client API for McpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpServiceClient interface {
	// Old: GET /api/v1/mcp/servers.
	ListServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*McpServerList, error)
	// Old: POST /api/v1/mcp/servers.
	CreateServer(ctx context.Context, in *McpServerInput, opts ...grpc.CallOption) (*McpServer, error)
	// Old: PUT /api/v1/mcp/servers/{id}.
	UpdateServer(ctx context.Context, in *McpServerRequest, opts ...grpc.CallOption) (*McpOk, error)
	// Old: DELETE /api/v1/mcp/servers/{id}.
	DeleteServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpOk, error)
	// Old: POST /api/v1/mcp/servers/{id}/toggle.
	ToggleServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpServer, error)
	// Old: POST /api/v1/mcp/servers/{id}/test.
	TestServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpTestResult, error)
	// Old: GET /api/v1/mcp/exposures.
	ListExposures(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*McpExposureList, error)
	// Old: POST /api/v1/chains/{id}/expose.
	Expose(ctx context.Context, in *ExposeMcpRequest, opts ...grpc.CallOption) (*ExposeMcpResponse, error)
	// Old: DELETE /api/v1/mcp/exposures/{id}.
	RemoveExposure(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpOk, error)
}

type mcpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpServiceClient(cc grpc.ClientConnInterface) McpServiceClient {
	return &mcpServiceClient{cc}
}

func (c *mcpServiceClient) ListServers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*McpServerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServerList)
	err := c.cc.Invoke(ctx, McpService_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) CreateServer(ctx context.Context, in *McpServerInput, opts ...grpc.CallOption) (*McpServer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServer)
	err := c.cc.Invoke(ctx, McpService_CreateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) UpdateServer(ctx context.Context, in *McpServerRequest, opts ...grpc.CallOption) (*McpOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpOk)
	err := c.cc.Invoke(ctx, McpService_UpdateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) DeleteServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpOk)
	err := c.cc.Invoke(ctx, McpService_DeleteServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) ToggleServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpServer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServer)
	err := c.cc.Invoke(ctx, McpService_ToggleServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) TestServer(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpTestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpTestResult)
	err := c.cc.Invoke(ctx, McpService_TestServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) ListExposures(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*McpExposureList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpExposureList)
	err := c.cc.Invoke(ctx, McpService_ListExposures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) Expose(ctx context.Context, in *ExposeMcpRequest, opts ...grpc.CallOption) (*ExposeMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExposeMcpResponse)
	err := c.cc.Invoke(ctx, McpService_Expose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpServiceClient) RemoveExposure(ctx context.Context, in *McpServerIdRequest, opts ...grpc.CallOption) (*McpOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpOk)
	err := c.cc.Invoke(ctx, McpService_RemoveExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpServiceServer is the server API for McpService service.
// All implementations must embed UnimplementedMcpServiceServer
// for forward compatibility.
type McpServiceServer interface {
	// Old: GET /api/v1/mcp/servers.
	ListServers(context.Context, *Empty) (*McpServerList, error)
	// Old: POST /api/v1/mcp/servers.
	CreateServer(context.Context, *McpServerInput) (*McpServer, error)
	// Old: PUT /api/v1/mcp/servers/{id}.
	UpdateServer(context.Context, *McpServerRequest) (*McpOk, error)
	// Old: DELETE /api/v1/mcp/servers/{id}.
	DeleteServer(context.Context, *McpServerIdRequest) (*McpOk, error)
	// Old: POST /api/v1/mcp/servers/{id}/toggle.
	ToggleServer(context.Context, *McpServerIdRequest) (*McpServer, error)
	// Old: POST /api/v1/mcp/servers/{id}/test.
	TestServer(context.Context, *McpServerIdRequest) (*McpTestResult, error)
	// Old: GET /api/v1/mcp/exposures.
	ListExposures(context.Context, *Empty) (*McpExposureList, error)
	// Old: POST /api/v1/chains/{id}/expose.
	Expose(context.Context, *ExposeMcpRequest) (*ExposeMcpResponse, error)
	// Old: DELETE /api/v1/mcp/exposures/{id}.
	RemoveExposure(context.Context, *McpServerIdRequest) (*McpOk, error)
	mustEmbedUnimplementedMcpServiceServer()
}

// UnimplementedMcpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMcpServiceServer struct{}

func (UnimplementedMcpServiceServer) ListServers(context.Context, *Empty) (*McpServerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedMcpServiceServer) CreateServer(context.Context, *McpServerInput) (*McpServer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedMcpServiceServer) UpdateServer(context.Context, *McpServerRequest) (*McpOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServer not implemented")
}
func (UnimplementedMcpServiceServer) DeleteServer(context.Context, *McpServerIdRequest) (*McpOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServer not implemented")
}
func (UnimplementedMcpServiceServer) ToggleServer(context.Context, *McpServerIdRequest) (*McpServer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleServer not implemented")
}
func (UnimplementedMcpServiceServer) TestServer(context.Context, *McpServerIdRequest) (*McpTestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestServer not implemented")
}
func (UnimplementedMcpServiceServer) ListExposures(context.Context, *Empty) (*McpExposureList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExposures not implemented")
}
func (UnimplementedMcpServiceServer) Expose(context.Context, *ExposeMcpRequest) (*ExposeMcpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expose not implemented")
}
func (UnimplementedMcpServiceServer) RemoveExposure(context.Context, *McpServerIdRequest) (*McpOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExposure not implemented")
}
func (UnimplementedMcpServiceServer) mustEmbedUnimplementedMcpServiceServer() {}
func (UnimplementedMcpServiceServer) testEmbeddedByValue()                    {}

// UnsafeMcpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpServiceServer will
// result in compilation errors.
type UnsafeMcpServiceServer interface {
	mustEmbedUnimplementedMcpServiceServer()
}

func RegisterMcpServiceServer(s grpc.ServiceRegistrar, srv McpServiceServer) {
	// If the following call pancis, it indicates UnimplementedMcpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&McpService_ServiceDesc, srv)
}

func _McpService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).ListServers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_CreateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).CreateServer(ctx, req.(*McpServerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_UpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).UpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_UpdateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).UpdateServer(ctx, req.(*McpServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_DeleteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).DeleteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_DeleteServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).DeleteServer(ctx, req.(*McpServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_ToggleServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).ToggleServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_ToggleServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).ToggleServer(ctx, req.(*McpServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_TestServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).TestServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_TestServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).TestServer(ctx, req.(*McpServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_ListExposures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).ListExposures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_ListExposures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).ListExposures(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_Expose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).Expose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_Expose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).Expose(ctx, req.(*ExposeMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpService_RemoveExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServiceServer).RemoveExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpService_RemoveExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServiceServer).RemoveExposure(ctx, req.(*McpServerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// McpService_ServiceDesc is the grpc.ServiceDesc for McpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.McpService",
	HandlerType: (*McpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServers",
			Handler:    _McpService_ListServers_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _McpService_CreateServer_Handler,
		},
		{
			MethodName: "UpdateServer",
			Handler:    _McpService_UpdateServer_Handler,
		},
		{
			MethodName: "DeleteServer",
			Handler:    _McpService_DeleteServer_Handler,
		},
		{
			MethodName: "ToggleServer",
			Handler:    _McpService_ToggleServer_Handler,
		},
		{
			MethodName: "TestServer",
			Handler:    _McpService_TestServer_Handler,
		},
		{
			MethodName: "ListExposures",
			Handler:    _McpService_ListExposures_Handler,
		},
		{
			MethodName: "Expose",
			Handler:    _McpService_Expose_Handler,
		},
		{
			MethodName: "RemoveExposure",
			Handler:    _McpService_RemoveExposure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/mcp.proto",
}
