// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/mcp.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMcpServiceCreateServer = "/baboflow.v1.McpService/CreateServer"
const OperationMcpServiceDeleteServer = "/baboflow.v1.McpService/DeleteServer"
const OperationMcpServiceExpose = "/baboflow.v1.McpService/Expose"
const OperationMcpServiceListExposures = "/baboflow.v1.McpService/ListExposures"
const OperationMcpServiceListServers = "/baboflow.v1.McpService/ListServers"
const OperationMcpServiceRemoveExposure = "/baboflow.v1.McpService/RemoveExposure"
const OperationMcpServiceTestServer = "/baboflow.v1.McpService/TestServer"
const OperationMcpServiceToggleServer = "/baboflow.v1.McpService/ToggleServer"
const OperationMcpServiceUpdateServer = "/baboflow.v1.McpService/UpdateServer"

type McpServiceHTTPServer interface {
	// CreateServer Old: POST /api/v1/mcp/servers.
	CreateServer(context.Context, *McpServerInput) (*McpServer, error)
	// DeleteServer Old: DELETE /api/v1/mcp/servers/{id}.
	DeleteServer(context.Context, *McpServerIdRequest) (*McpOk, error)
	// Expose Old: POST /api/v1/chains/{id}/expose.
	Expose(context.Context, *ExposeMcpRequest) (*ExposeMcpResponse, error)
	// ListExposures Old: GET /api/v1/mcp/exposures.
	ListExposures(context.Context, *Empty) (*McpExposureList, error)
	// ListServers Old: GET /api/v1/mcp/servers.
	ListServers(context.Context, *Empty) (*McpServerList, error)
	// RemoveExposure Old: DELETE /api/v1/mcp/exposures/{id}.
	RemoveExposure(context.Context, *McpServerIdRequest) (*McpOk, error)
	// TestServer Old: POST /api/v1/mcp/servers/{id}/test.
	TestServer(context.Context, *McpServerIdRequest) (*McpTestResult, error)
	// ToggleServer Old: POST /api/v1/mcp/servers/{id}/toggle.
	ToggleServer(context.Context, *McpServerIdRequest) (*McpServer, error)
	// UpdateServer Old: PUT /api/v1/mcp/servers/{id}.
	UpdateServer(context.Context, *McpServerRequest) (*McpOk, error)
}

func RegisterMcpServiceHTTPServer(s *http.Server, srv McpServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/mcp/servers", _McpService_ListServers0_HTTP_Handler(srv))
	r.POST("/api/v1/mcp/servers", _McpService_CreateServer0_HTTP_Handler(srv))
	r.PUT("/api/v1/mcp/servers/{id}", _McpService_UpdateServer0_HTTP_Handler(srv))
	r.DELETE("/api/v1/mcp/servers/{id}", _McpService_DeleteServer0_HTTP_Handler(srv))
	r.POST("/api/v1/mcp/servers/{id}/toggle", _McpService_ToggleServer0_HTTP_Handler(srv))
	r.POST("/api/v1/mcp/servers/{id}/test", _McpService_TestServer0_HTTP_Handler(srv))
	r.GET("/api/v1/mcp/exposures", _McpService_ListExposures0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{chainId}/expose", _McpService_Expose0_HTTP_Handler(srv))
	r.DELETE("/api/v1/mcp/exposures/{id}", _McpService_RemoveExposure0_HTTP_Handler(srv))
}

func _McpService_ListServers0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceListServers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServers(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpServerList)
		return ctx.Result(200, reply)
	}
}

func _McpService_CreateServer0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceCreateServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateServer(ctx, req.(*McpServerInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpServer)
		return ctx.Result(200, reply)
	}
}

func _McpService_UpdateServer0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceUpdateServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateServer(ctx, req.(*McpServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpOk)
		return ctx.Result(200, reply)
	}
}

func _McpService_DeleteServer0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceDeleteServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteServer(ctx, req.(*McpServerIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpOk)
		return ctx.Result(200, reply)
	}
}

func _McpService_ToggleServer0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceToggleServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleServer(ctx, req.(*McpServerIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpServer)
		return ctx.Result(200, reply)
	}
}

func _McpService_TestServer0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceTestServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestServer(ctx, req.(*McpServerIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpTestResult)
		return ctx.Result(200, reply)
	}
}

func _McpService_ListExposures0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceListExposures)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExposures(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpExposureList)
		return ctx.Result(200, reply)
	}
}

func _McpService_Expose0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExposeMcpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceExpose)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Expose(ctx, req.(*ExposeMcpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExposeMcpResponse)
		return ctx.Result(200, reply)
	}
}

func _McpService_RemoveExposure0_HTTP_Handler(srv McpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in McpServerIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMcpServiceRemoveExposure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveExposure(ctx, req.(*McpServerIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*McpOk)
		return ctx.Result(200, reply)
	}
}

type McpServiceHTTPClient interface {
	// CreateServer Old: POST /api/v1/mcp/servers.
	CreateServer(ctx context.Context, req *McpServerInput, opts ...http.CallOption) (rsp *McpServer, err error)
	// DeleteServer Old: DELETE /api/v1/mcp/servers/{id}.
	DeleteServer(ctx context.Context, req *McpServerIdRequest, opts ...http.CallOption) (rsp *McpOk, err error)
	// Expose Old: POST /api/v1/chains/{id}/expose.
	Expose(ctx context.Context, req *ExposeMcpRequest, opts ...http.CallOption) (rsp *ExposeMcpResponse, err error)
	// ListExposures Old: GET /api/v1/mcp/exposures.
	ListExposures(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *McpExposureList, err error)
	// ListServers Old: GET /api/v1/mcp/servers.
	ListServers(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *McpServerList, err error)
	// RemoveExposure Old: DELETE /api/v1/mcp/exposures/{id}.
	RemoveExposure(ctx context.Context, req *McpServerIdRequest, opts ...http.CallOption) (rsp *McpOk, err error)
	// TestServer Old: POST /api/v1/mcp/servers/{id}/test.
	TestServer(ctx context.Context, req *McpServerIdRequest, opts ...http.CallOption) (rsp *McpTestResult, err error)
	// ToggleServer Old: POST /api/v1/mcp/servers/{id}/toggle.
	ToggleServer(ctx context.Context, req *McpServerIdRequest, opts ...http.CallOption) (rsp *McpServer, err error)
	// UpdateServer Old: PUT /api/v1/mcp/servers/{id}.
	UpdateServer(ctx context.Context, req *McpServerRequest, opts ...http.CallOption) (rsp *McpOk, err error)
}

type McpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMcpServiceHTTPClient(client *http.Client) McpServiceHTTPClient {
	return &McpServiceHTTPClientImpl{client}
}

// CreateServer Old: POST /api/v1/mcp/servers.
func (c *McpServiceHTTPClientImpl) CreateServer(ctx context.Context, in *McpServerInput, opts ...http.CallOption) (*McpServer, error) {
	var out McpServer
	pattern := "/api/v1/mcp/servers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMcpServiceCreateServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteServer Old: DELETE /api/v1/mcp/servers/{id}.
func (c *McpServiceHTTPClientImpl) DeleteServer(ctx context.Context, in *McpServerIdRequest, opts ...http.CallOption) (*McpOk, error) {
	var out McpOk
	pattern := "/api/v1/mcp/servers/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMcpServiceDeleteServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Expose Old: POST /api/v1/chains/{id}/expose.
func (c *McpServiceHTTPClientImpl) Expose(ctx context.Context, in *ExposeMcpRequest, opts ...http.CallOption) (*ExposeMcpResponse, error) {
	var out ExposeMcpResponse
	pattern := "/api/v1/rule-chains/{chainId}/expose"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMcpServiceExpose))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListExposures Old: GET /api/v1/mcp/exposures.
func (c *McpServiceHTTPClientImpl) ListExposures(ctx context.Context, in *Empty, opts ...http.CallOption) (*McpExposureList, error) {
	var out McpExposureList
	pattern := "/api/v1/mcp/exposures"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMcpServiceListExposures))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListServers Old: GET /api/v1/mcp/servers.
func (c *McpServiceHTTPClientImpl) ListServers(ctx context.Context, in *Empty, opts ...http.CallOption) (*McpServerList, error) {
	var out McpServerList
	pattern := "/api/v1/mcp/servers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMcpServiceListServers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveExposure Old: DELETE /api/v1/mcp/exposures/{id}.
func (c *McpServiceHTTPClientImpl) RemoveExposure(ctx context.Context, in *McpServerIdRequest, opts ...http.CallOption) (*McpOk, error) {
	var out McpOk
	pattern := "/api/v1/mcp/exposures/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMcpServiceRemoveExposure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TestServer Old: POST /api/v1/mcp/servers/{id}/test.
func (c *McpServiceHTTPClientImpl) TestServer(ctx context.Context, in *McpServerIdRequest, opts ...http.CallOption) (*McpTestResult, error) {
	var out McpTestResult
	pattern := "/api/v1/mcp/servers/{id}/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMcpServiceTestServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleServer Old: POST /api/v1/mcp/servers/{id}/toggle.
func (c *McpServiceHTTPClientImpl) ToggleServer(ctx context.Context, in *McpServerIdRequest, opts ...http.CallOption) (*McpServer, error) {
	var out McpServer
	pattern := "/api/v1/mcp/servers/{id}/toggle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMcpServiceToggleServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateServer Old: PUT /api/v1/mcp/servers/{id}.
func (c *McpServiceHTTPClientImpl) UpdateServer(ctx context.Context, in *McpServerRequest, opts ...http.CallOption) (*McpOk, error) {
	var out McpOk
	pattern := "/api/v1/mcp/servers/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMcpServiceUpdateServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
