// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/rulechain.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuleChainService_List_FullMethodName         = "/baboflow.v1.RuleChainService/List"
	RuleChainService_Create_FullMethodName       = "/baboflow.v1.RuleChainService/Create"
	RuleChainService_Get_FullMethodName          = "/baboflow.v1.RuleChainService/Get"
	RuleChainService_Update_FullMethodName       = "/baboflow.v1.RuleChainService/Update"
	RuleChainService_Delete_FullMethodName       = "/baboflow.v1.RuleChainService/Delete"
	RuleChainService_Validate_FullMethodName     = "/baboflow.v1.RuleChainService/Validate"
	RuleChainService_Publish_FullMethodName      = "/baboflow.v1.RuleChainService/Publish"
	RuleChainService_Offline_FullMethodName      = "/baboflow.v1.RuleChainService/Offline"
	RuleChainService_ListVersions_FullMethodName = "/baboflow.v1.RuleChainService/ListVersions"
	RuleChainService_Rollback_FullMethodName     = "/baboflow.v1.RuleChainService/Rollback"
	RuleChainService_Export_FullMethodName       = "/baboflow.v1.RuleChainService/Export"
	RuleChainService_Import_FullMethodName       = "/baboflow.v1.RuleChainService/Import"
	RuleChainService_Run_FullMethodName          = "/baboflow.v1.RuleChainService/Run"
	RuleChainService_Debug_FullMethodName        = "/baboflow.v1.RuleChainService/Debug"
	RuleChainService_ListRuns_FullMethodName     = "/baboflow.v1.RuleChainService/ListRuns"
	RuleChainService_GetRun_FullMethodName       = "/baboflow.v1.RuleChainService/GetRun"
)

// RuleChainServiceClient is the client API for RuleChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleChainServiceClient interface {
	// Old: GET /api/v1/chains?status=&keyword=&page=&pageSize=.
	List(ctx context.Context, in *RuleChainListRequest, opts ...grpc.CallOption) (*RuleChainListResponse, error)
	// Old: POST /api/v1/chains.
	Create(ctx context.Context, in *RuleChainInput, opts ...grpc.CallOption) (*RuleChain, error)
	// Old: GET /api/v1/chains/{id}.
	Get(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChain, error)
	// Old: PUT /api/v1/chains/{id}.
	Update(ctx context.Context, in *RuleChainUpdateRequest, opts ...grpc.CallOption) (*RuleChainOk, error)
	// Old: DELETE /api/v1/chains/{id}.
	Delete(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainOk, error)
	// Old: POST /api/v1/chains/validate.
	Validate(ctx context.Context, in *ValidateRuleChainRequest, opts ...grpc.CallOption) (*ValidateRuleChainResponse, error)
	// Old: POST /api/v1/chains/{id}/publish.
	Publish(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*PublishRuleChainResponse, error)
	// Old: POST /api/v1/chains/{id}/offline.
	Offline(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainOk, error)
	// Old: GET /api/v1/chains/{id}/versions.
	ListVersions(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainVersionList, error)
	// Old: POST /api/v1/chains/{id}/rollback.
	Rollback(ctx context.Context, in *RollbackRuleChainRequest, opts ...grpc.CallOption) (*RuleChainOk, error)
	// Old: GET /api/v1/chains/{id}/export.
	Export(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainExport, error)
	// Old: POST /api/v1/chains/import.
	Import(ctx context.Context, in *RuleChainExport, opts ...grpc.CallOption) (*RuleChain, error)
	// Old: POST /api/v1/chains/{id}/run.
	Run(ctx context.Context, in *RunRuleChainRequest, opts ...grpc.CallOption) (*ImmediateRunResult, error)
	// Old: POST /api/v1/chains/{id}/debug.
	Debug(ctx context.Context, in *RunRuleChainRequest, opts ...grpc.CallOption) (*ImmediateRunResult, error)
	// Old: GET /api/v1/chains/runs?chainId=&status=&page=&pageSize=.
	ListRuns(ctx context.Context, in *RuleChainRunListRequest, opts ...grpc.CallOption) (*RuleChainRunListResponse, error)
	// Old: GET /api/v1/chains/runs/{runId}.
	GetRun(ctx context.Context, in *RuleChainRunIdRequest, opts ...grpc.CallOption) (*RuleChainRun, error)
}

type ruleChainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleChainServiceClient(cc grpc.ClientConnInterface) RuleChainServiceClient {
	return &ruleChainServiceClient{cc}
}

func (c *ruleChainServiceClient) List(ctx context.Context, in *RuleChainListRequest, opts ...grpc.CallOption) (*RuleChainListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainListResponse)
	err := c.cc.Invoke(ctx, RuleChainService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Create(ctx context.Context, in *RuleChainInput, opts ...grpc.CallOption) (*RuleChain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChain)
	err := c.cc.Invoke(ctx, RuleChainService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Get(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChain)
	err := c.cc.Invoke(ctx, RuleChainService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Update(ctx context.Context, in *RuleChainUpdateRequest, opts ...grpc.CallOption) (*RuleChainOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainOk)
	err := c.cc.Invoke(ctx, RuleChainService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Delete(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainOk)
	err := c.cc.Invoke(ctx, RuleChainService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Validate(ctx context.Context, in *ValidateRuleChainRequest, opts ...grpc.CallOption) (*ValidateRuleChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRuleChainResponse)
	err := c.cc.Invoke(ctx, RuleChainService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Publish(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*PublishRuleChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishRuleChainResponse)
	err := c.cc.Invoke(ctx, RuleChainService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Offline(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainOk)
	err := c.cc.Invoke(ctx, RuleChainService_Offline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) ListVersions(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainVersionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainVersionList)
	err := c.cc.Invoke(ctx, RuleChainService_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Rollback(ctx context.Context, in *RollbackRuleChainRequest, opts ...grpc.CallOption) (*RuleChainOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainOk)
	err := c.cc.Invoke(ctx, RuleChainService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Export(ctx context.Context, in *RuleChainIdRequest, opts ...grpc.CallOption) (*RuleChainExport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainExport)
	err := c.cc.Invoke(ctx, RuleChainService_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Import(ctx context.Context, in *RuleChainExport, opts ...grpc.CallOption) (*RuleChain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChain)
	err := c.cc.Invoke(ctx, RuleChainService_Import_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Run(ctx context.Context, in *RunRuleChainRequest, opts ...grpc.CallOption) (*ImmediateRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImmediateRunResult)
	err := c.cc.Invoke(ctx, RuleChainService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) Debug(ctx context.Context, in *RunRuleChainRequest, opts ...grpc.CallOption) (*ImmediateRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImmediateRunResult)
	err := c.cc.Invoke(ctx, RuleChainService_Debug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) ListRuns(ctx context.Context, in *RuleChainRunListRequest, opts ...grpc.CallOption) (*RuleChainRunListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainRunListResponse)
	err := c.cc.Invoke(ctx, RuleChainService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) GetRun(ctx context.Context, in *RuleChainRunIdRequest, opts ...grpc.CallOption) (*RuleChainRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleChainRun)
	err := c.cc.Invoke(ctx, RuleChainService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleChainServiceServer is the server API for RuleChainService service.
// All implementations must embed UnimplementedRuleChainServiceServer
// for forward compatibility.
type RuleChainServiceServer interface {
	// Old: GET /api/v1/chains?status=&keyword=&page=&pageSize=.
	List(context.Context, *RuleChainListRequest) (*RuleChainListResponse, error)
	// Old: POST /api/v1/chains.
	Create(context.Context, *RuleChainInput) (*RuleChain, error)
	// Old: GET /api/v1/chains/{id}.
	Get(context.Context, *RuleChainIdRequest) (*RuleChain, error)
	// Old: PUT /api/v1/chains/{id}.
	Update(context.Context, *RuleChainUpdateRequest) (*RuleChainOk, error)
	// Old: DELETE /api/v1/chains/{id}.
	Delete(context.Context, *RuleChainIdRequest) (*RuleChainOk, error)
	// Old: POST /api/v1/chains/validate.
	Validate(context.Context, *ValidateRuleChainRequest) (*ValidateRuleChainResponse, error)
	// Old: POST /api/v1/chains/{id}/publish.
	Publish(context.Context, *RuleChainIdRequest) (*PublishRuleChainResponse, error)
	// Old: POST /api/v1/chains/{id}/offline.
	Offline(context.Context, *RuleChainIdRequest) (*RuleChainOk, error)
	// Old: GET /api/v1/chains/{id}/versions.
	ListVersions(context.Context, *RuleChainIdRequest) (*RuleChainVersionList, error)
	// Old: POST /api/v1/chains/{id}/rollback.
	Rollback(context.Context, *RollbackRuleChainRequest) (*RuleChainOk, error)
	// Old: GET /api/v1/chains/{id}/export.
	Export(context.Context, *RuleChainIdRequest) (*RuleChainExport, error)
	// Old: POST /api/v1/chains/import.
	Import(context.Context, *RuleChainExport) (*RuleChain, error)
	// Old: POST /api/v1/chains/{id}/run.
	Run(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error)
	// Old: POST /api/v1/chains/{id}/debug.
	Debug(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error)
	// Old: GET /api/v1/chains/runs?chainId=&status=&page=&pageSize=.
	ListRuns(context.Context, *RuleChainRunListRequest) (*RuleChainRunListResponse, error)
	// Old: GET /api/v1/chains/runs/{runId}.
	GetRun(context.Context, *RuleChainRunIdRequest) (*RuleChainRun, error)
	mustEmbedUnimplementedRuleChainServiceServer()
}

// UnimplementedRuleChainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleChainServiceServer struct{}

func (UnimplementedRuleChainServiceServer) List(context.Context, *RuleChainListRequest) (*RuleChainListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRuleChainServiceServer) Create(context.Context, *RuleChainInput) (*RuleChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRuleChainServiceServer) Get(context.Context, *RuleChainIdRequest) (*RuleChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRuleChainServiceServer) Update(context.Context, *RuleChainUpdateRequest) (*RuleChainOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRuleChainServiceServer) Delete(context.Context, *RuleChainIdRequest) (*RuleChainOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRuleChainServiceServer) Validate(context.Context, *ValidateRuleChainRequest) (*ValidateRuleChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedRuleChainServiceServer) Publish(context.Context, *RuleChainIdRequest) (*PublishRuleChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedRuleChainServiceServer) Offline(context.Context, *RuleChainIdRequest) (*RuleChainOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Offline not implemented")
}
func (UnimplementedRuleChainServiceServer) ListVersions(context.Context, *RuleChainIdRequest) (*RuleChainVersionList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedRuleChainServiceServer) Rollback(context.Context, *RollbackRuleChainRequest) (*RuleChainOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedRuleChainServiceServer) Export(context.Context, *RuleChainIdRequest) (*RuleChainExport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedRuleChainServiceServer) Import(context.Context, *RuleChainExport) (*RuleChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedRuleChainServiceServer) Run(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRuleChainServiceServer) Debug(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedRuleChainServiceServer) ListRuns(context.Context, *RuleChainRunListRequest) (*RuleChainRunListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedRuleChainServiceServer) GetRun(context.Context, *RuleChainRunIdRequest) (*RuleChainRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRuleChainServiceServer) mustEmbedUnimplementedRuleChainServiceServer() {}
func (UnimplementedRuleChainServiceServer) testEmbeddedByValue()                          {}

// UnsafeRuleChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleChainServiceServer will
// result in compilation errors.
type UnsafeRuleChainServiceServer interface {
	mustEmbedUnimplementedRuleChainServiceServer()
}

func RegisterRuleChainServiceServer(s grpc.ServiceRegistrar, srv RuleChainServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuleChainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleChainService_ServiceDesc, srv)
}

func _RuleChainService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).List(ctx, req.(*RuleChainListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Create(ctx, req.(*RuleChainInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Get(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Update(ctx, req.(*RuleChainUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Delete(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Validate(ctx, req.(*ValidateRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Publish(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Offline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Offline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Offline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Offline(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).ListVersions(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Rollback(ctx, req.(*RollbackRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Export(ctx, req.(*RuleChainIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainExport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Import_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Import(ctx, req.(*RuleChainExport))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Run(ctx, req.(*RunRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_Debug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).Debug(ctx, req.(*RunRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainRunListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).ListRuns(ctx, req.(*RuleChainRunListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleChainRunIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleChainService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).GetRun(ctx, req.(*RuleChainRunIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleChainService_ServiceDesc is the grpc.ServiceDesc for RuleChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.RuleChainService",
	HandlerType: (*RuleChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RuleChainService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RuleChainService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RuleChainService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RuleChainService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RuleChainService_Delete_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _RuleChainService_Validate_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _RuleChainService_Publish_Handler,
		},
		{
			MethodName: "Offline",
			Handler:    _RuleChainService_Offline_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _RuleChainService_ListVersions_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _RuleChainService_Rollback_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _RuleChainService_Export_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _RuleChainService_Import_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _RuleChainService_Run_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _RuleChainService_Debug_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _RuleChainService_ListRuns_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RuleChainService_GetRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/rulechain.proto",
}
