// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/rulechain.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,4,opt,name=inputSchema,proto3" json:"inputSchema,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	DebugMode     bool                   `protobuf:"varint,8,opt,name=debugMode,proto3" json:"debugMode,omitempty"`
	Dsl           *structpb.Struct       `protobuf:"bytes,9,opt,name=dsl,proto3" json:"dsl,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChain) Reset() {
	*x = RuleChain{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChain) ProtoMessage() {}

func (x *RuleChain) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChain.ProtoReflect.Descriptor instead.
func (*RuleChain) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{0}
}

func (x *RuleChain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleChain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleChain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleChain) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *RuleChain) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleChain) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleChain) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleChain) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *RuleChain) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

func (x *RuleChain) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RuleChain) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RuleChainListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	DebugMode     bool                   `protobuf:"varint,7,opt,name=debugMode,proto3" json:"debugMode,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainListItem) Reset() {
	*x = RuleChainListItem{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainListItem) ProtoMessage() {}

func (x *RuleChainListItem) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainListItem.ProtoReflect.Descriptor instead.
func (*RuleChainListItem) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{1}
}

func (x *RuleChainListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleChainListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleChainListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleChainListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleChainListItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleChainListItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleChainListItem) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *RuleChainListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RuleChainInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=inputSchema,proto3" json:"inputSchema,omitempty"`
	Dsl           *structpb.Struct       `protobuf:"bytes,4,opt,name=dsl,proto3" json:"dsl,omitempty"`
	DebugMode     bool                   `protobuf:"varint,5,opt,name=debugMode,proto3" json:"debugMode,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainInput) Reset() {
	*x = RuleChainInput{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainInput) ProtoMessage() {}

func (x *RuleChainInput) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainInput.ProtoReflect.Descriptor instead.
func (*RuleChainInput) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{2}
}

func (x *RuleChainInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleChainInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleChainInput) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *RuleChainInput) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

func (x *RuleChainInput) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *RuleChainInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RuleChainIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainIdRequest) Reset() {
	*x = RuleChainIdRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainIdRequest) ProtoMessage() {}

func (x *RuleChainIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainIdRequest.ProtoReflect.Descriptor instead.
func (*RuleChainIdRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{3}
}

func (x *RuleChainIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RuleChainUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,4,opt,name=inputSchema,proto3" json:"inputSchema,omitempty"`
	Dsl           *structpb.Struct       `protobuf:"bytes,5,opt,name=dsl,proto3" json:"dsl,omitempty"`
	DebugMode     bool                   `protobuf:"varint,6,opt,name=debugMode,proto3" json:"debugMode,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainUpdateRequest) Reset() {
	*x = RuleChainUpdateRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainUpdateRequest) ProtoMessage() {}

func (x *RuleChainUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainUpdateRequest.ProtoReflect.Descriptor instead.
func (*RuleChainUpdateRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{4}
}

func (x *RuleChainUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleChainUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleChainUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleChainUpdateRequest) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *RuleChainUpdateRequest) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

func (x *RuleChainUpdateRequest) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

func (x *RuleChainUpdateRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RuleChainListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainListRequest) Reset() {
	*x = RuleChainListRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainListRequest) ProtoMessage() {}

func (x *RuleChainListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainListRequest.ProtoReflect.Descriptor instead.
func (*RuleChainListRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{5}
}

func (x *RuleChainListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *RuleChainListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleChainListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type RuleChainListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RuleChainListItem   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainListResponse) Reset() {
	*x = RuleChainListResponse{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainListResponse) ProtoMessage() {}

func (x *RuleChainListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainListResponse.ProtoReflect.Descriptor instead.
func (*RuleChainListResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{6}
}

func (x *RuleChainListResponse) GetList() []*RuleChainListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RuleChainListResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ValidateRuleChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsl           *structpb.Struct       `protobuf:"bytes,1,opt,name=dsl,proto3" json:"dsl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleChainRequest) Reset() {
	*x = ValidateRuleChainRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleChainRequest) ProtoMessage() {}

func (x *ValidateRuleChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleChainRequest.ProtoReflect.Descriptor instead.
func (*ValidateRuleChainRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRuleChainRequest) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

type ValidateRuleChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleChainResponse) Reset() {
	*x = ValidateRuleChainResponse{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleChainResponse) ProtoMessage() {}

func (x *ValidateRuleChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleChainResponse.ProtoReflect.Descriptor instead.
func (*ValidateRuleChainResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateRuleChainResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateRuleChainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RuleChainVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Dsl           *structpb.Struct       `protobuf:"bytes,4,opt,name=dsl,proto3" json:"dsl,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,5,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainVersion) Reset() {
	*x = RuleChainVersion{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainVersion) ProtoMessage() {}

func (x *RuleChainVersion) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainVersion.ProtoReflect.Descriptor instead.
func (*RuleChainVersion) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{9}
}

func (x *RuleChainVersion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RuleChainVersion) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *RuleChainVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleChainVersion) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

func (x *RuleChainVersion) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type RuleChainVersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RuleChainVersion    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainVersionList) Reset() {
	*x = RuleChainVersionList{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainVersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainVersionList) ProtoMessage() {}

func (x *RuleChainVersionList) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainVersionList.ProtoReflect.Descriptor instead.
func (*RuleChainVersionList) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{10}
}

func (x *RuleChainVersionList) GetList() []*RuleChainVersion {
	if x != nil {
		return x.List
	}
	return nil
}

type RollbackRuleChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRuleChainRequest) Reset() {
	*x = RollbackRuleChainRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRuleChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRuleChainRequest) ProtoMessage() {}

func (x *RollbackRuleChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRuleChainRequest.ProtoReflect.Descriptor instead.
func (*RollbackRuleChainRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{11}
}

func (x *RollbackRuleChainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RollbackRuleChainRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PublishRuleChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRuleChainResponse) Reset() {
	*x = PublishRuleChainResponse{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRuleChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRuleChainResponse) ProtoMessage() {}

func (x *PublishRuleChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRuleChainResponse.ProtoReflect.Descriptor instead.
func (*PublishRuleChainResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{12}
}

func (x *PublishRuleChainResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RuleChainExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=inputSchema,proto3" json:"inputSchema,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Dsl           *structpb.Struct       `protobuf:"bytes,5,opt,name=dsl,proto3" json:"dsl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainExport) Reset() {
	*x = RuleChainExport{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainExport) ProtoMessage() {}

func (x *RuleChainExport) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainExport.ProtoReflect.Descriptor instead.
func (*RuleChainExport) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{13}
}

func (x *RuleChainExport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleChainExport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleChainExport) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *RuleChainExport) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleChainExport) GetDsl() *structpb.Struct {
	if x != nil {
		return x.Dsl
	}
	return nil
}

type RunRuleChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRuleChainRequest) Reset() {
	*x = RunRuleChainRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRuleChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRuleChainRequest) ProtoMessage() {}

func (x *RunRuleChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRuleChainRequest.ProtoReflect.Descriptor instead.
func (*RunRuleChainRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{14}
}

func (x *RunRuleChainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunRuleChainRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *RunRuleChainRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RunRuleChainRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ImmediateRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=runId,proto3" json:"runId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	NodeTrace     []*NodeTrace           `protobuf:"bytes,5,rep,name=nodeTrace,proto3" json:"nodeTrace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImmediateRunResult) Reset() {
	*x = ImmediateRunResult{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmediateRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmediateRunResult) ProtoMessage() {}

func (x *ImmediateRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmediateRunResult.ProtoReflect.Descriptor instead.
func (*ImmediateRunResult) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{15}
}

func (x *ImmediateRunResult) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *ImmediateRunResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImmediateRunResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ImmediateRunResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ImmediateRunResult) GetNodeTrace() []*NodeTrace {
	if x != nil {
		return x.NodeTrace
	}
	return nil
}

type RuleChainRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Trigger       string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,9,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	NodeTrace     []*NodeTrace           `protobuf:"bytes,10,rep,name=nodeTrace,proto3" json:"nodeTrace,omitempty"`
	TaskId        *int64                 `protobuf:"varint,11,opt,name=taskId,proto3,oneof" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainRun) Reset() {
	*x = RuleChainRun{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainRun) ProtoMessage() {}

func (x *RuleChainRun) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainRun.ProtoReflect.Descriptor instead.
func (*RuleChainRun) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{16}
}

func (x *RuleChainRun) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RuleChainRun) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *RuleChainRun) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *RuleChainRun) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RuleChainRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RuleChainRun) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RuleChainRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RuleChainRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RuleChainRun) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *RuleChainRun) GetNodeTrace() []*NodeTrace {
	if x != nil {
		return x.NodeTrace
	}
	return nil
}

func (x *RuleChainRun) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

type NodeTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	FlowType      string                 `protobuf:"bytes,2,opt,name=flowType,proto3" json:"flowType,omitempty"`
	RelationType  string                 `protobuf:"bytes,3,opt,name=relationType,proto3" json:"relationType,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	In            string                 `protobuf:"bytes,5,opt,name=in,proto3" json:"in,omitempty"`
	Out           string                 `protobuf:"bytes,6,opt,name=out,proto3" json:"out,omitempty"`
	Input         *TraceMessage          `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Output        *TraceMessage          `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	Err           string                 `protobuf:"bytes,10,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeTrace) Reset() {
	*x = NodeTrace{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTrace) ProtoMessage() {}

func (x *NodeTrace) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTrace.ProtoReflect.Descriptor instead.
func (*NodeTrace) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{17}
}

func (x *NodeTrace) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeTrace) GetFlowType() string {
	if x != nil {
		return x.FlowType
	}
	return ""
}

func (x *NodeTrace) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *NodeTrace) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *NodeTrace) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *NodeTrace) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *NodeTrace) GetInput() *TraceMessage {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *NodeTrace) GetOutput() *TraceMessage {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *NodeTrace) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *NodeTrace) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type TraceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=dataType,proto3" json:"dataType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceMessage) Reset() {
	*x = TraceMessage{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceMessage) ProtoMessage() {}

func (x *TraceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceMessage.ProtoReflect.Descriptor instead.
func (*TraceMessage) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{18}
}

func (x *TraceMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TraceMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TraceMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TraceMessage) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

type RuleChainRunListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainRunListRequest) Reset() {
	*x = RuleChainRunListRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainRunListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainRunListRequest) ProtoMessage() {}

func (x *RuleChainRunListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainRunListRequest.ProtoReflect.Descriptor instead.
func (*RuleChainRunListRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{19}
}

func (x *RuleChainRunListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *RuleChainRunListRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *RuleChainRunListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RuleChainRunListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RuleChainRun        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainRunListResponse) Reset() {
	*x = RuleChainRunListResponse{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainRunListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainRunListResponse) ProtoMessage() {}

func (x *RuleChainRunListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainRunListResponse.ProtoReflect.Descriptor instead.
func (*RuleChainRunListResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{20}
}

func (x *RuleChainRunListResponse) GetList() []*RuleChainRun {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RuleChainRunListResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type RuleChainRunIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=runId,proto3" json:"runId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainRunIdRequest) Reset() {
	*x = RuleChainRunIdRequest{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainRunIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainRunIdRequest) ProtoMessage() {}

func (x *RuleChainRunIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainRunIdRequest.ProtoReflect.Descriptor instead.
func (*RuleChainRunIdRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{21}
}

func (x *RuleChainRunIdRequest) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type RuleChainOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleChainOk) Reset() {
	*x = RuleChainOk{}
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleChainOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleChainOk) ProtoMessage() {}

func (x *RuleChainOk) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_rulechain_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleChainOk.ProtoReflect.Descriptor instead.
func (*RuleChainOk) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_rulechain_proto_rawDescGZIP(), []int{22}
}

func (x *RuleChainOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_baboflow_v1_rulechain_proto protoreflect.FileDescriptor

const file_baboflow_v1_rulechain_proto_rawDesc = "" +
	"\n" +
	"\x1bbaboflow/v1/rulechain.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18baboflow/v1/common.proto\"\xdb\x02\n" +
	"\tRuleChain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\vinputSchema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1c\n" +
	"\tdebugMode\x18\b \x01(\bR\tdebugMode\x12)\n" +
	"\x03dsl\x18\t \x01(\v2\x17.google.protobuf.StructR\x03dsl\x12\x1c\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\"\xdf\x01\n" +
	"\x11RuleChainListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1c\n" +
	"\tdebugMode\x18\a \x01(\bR\tdebugMode\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\"\xe2\x01\n" +
	"\x0eRuleChainInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\vinputSchema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12)\n" +
	"\x03dsl\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x03dsl\x12\x1c\n" +
	"\tdebugMode\x18\x05 \x01(\bR\tdebugMode\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"$\n" +
	"\x12RuleChainIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfa\x01\n" +
	"\x16RuleChainUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\vinputSchema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12)\n" +
	"\x03dsl\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x03dsl\x12\x1c\n" +
	"\tdebugMode\x18\x06 \x01(\bR\tdebugMode\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"v\n" +
	"\x14RuleChainListRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.baboflow.v1.PageRequestR\x04page\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"z\n" +
	"\x15RuleChainListResponse\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.baboflow.v1.RuleChainListItemR\x04list\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.baboflow.v1.PageResponseR\x04page\"E\n" +
	"\x18ValidateRuleChainRequest\x12)\n" +
	"\x03dsl\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x03dsl\"G\n" +
	"\x19ValidateRuleChainResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa3\x01\n" +
	"\x10RuleChainVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\achainId\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12)\n" +
	"\x03dsl\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x03dsl\x12 \n" +
	"\vpublishedAt\x18\x05 \x01(\tR\vpublishedAt\"I\n" +
	"\x14RuleChainVersionList\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.baboflow.v1.RuleChainVersionR\x04list\"D\n" +
	"\x18RollbackRuleChainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"4\n" +
	"\x18PublishRuleChainResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"\xc7\x01\n" +
	"\x0fRuleChainExport\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\vinputSchema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12)\n" +
	"\x03dsl\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x03dsl\"\xde\x01\n" +
	"\x13RunRuleChainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdataType\x18\x02 \x01(\tR\bdataType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..baboflow.v1.RunRuleChainRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x12ImmediateRunResult\x12\x14\n" +
	"\x05runId\x18\x01 \x01(\x03R\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x124\n" +
	"\tnodeTrace\x18\x05 \x03(\v2\x16.baboflow.v1.NodeTraceR\tnodeTrace\"\xfc\x02\n" +
	"\fRuleChainRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\achainId\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05input\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12/\n" +
	"\x06output\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1c\n" +
	"\tstartedAt\x18\b \x01(\tR\tstartedAt\x12\x1e\n" +
	"\n" +
	"finishedAt\x18\t \x01(\tR\n" +
	"finishedAt\x124\n" +
	"\tnodeTrace\x18\n" +
	" \x03(\v2\x16.baboflow.v1.NodeTraceR\tnodeTrace\x12\x1b\n" +
	"\x06taskId\x18\v \x01(\x03H\x00R\x06taskId\x88\x01\x01B\t\n" +
	"\a_taskId\"\xaf\x02\n" +
	"\tNodeTrace\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bflowType\x18\x02 \x01(\tR\bflowType\x12\"\n" +
	"\frelationType\x18\x03 \x01(\tR\frelationType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x0e\n" +
	"\x02in\x18\x05 \x01(\tR\x02in\x12\x10\n" +
	"\x03out\x18\x06 \x01(\tR\x03out\x12/\n" +
	"\x05input\x18\a \x01(\v2\x19.baboflow.v1.TraceMessageR\x05input\x121\n" +
	"\x06output\x18\b \x01(\v2\x19.baboflow.v1.TraceMessageR\x06output\x12\x1e\n" +
	"\n" +
	"durationMs\x18\t \x01(\x03R\n" +
	"durationMs\x12\x10\n" +
	"\x03err\x18\n" +
	" \x01(\tR\x03err\"\xd2\x01\n" +
	"\fTraceMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12C\n" +
	"\bmetadata\x18\x02 \x03(\v2'.baboflow.v1.TraceMessage.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bdataType\x18\x04 \x01(\tR\bdataType\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x17RuleChainRunListRequest\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.baboflow.v1.PageRequestR\x04page\x12\x18\n" +
	"\achainId\x18\x02 \x01(\tR\achainId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"x\n" +
	"\x18RuleChainRunListResponse\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.baboflow.v1.RuleChainRunR\x04list\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.baboflow.v1.PageResponseR\x04page\"-\n" +
	"\x15RuleChainRunIdRequest\x12\x14\n" +
	"\x05runId\x18\x01 \x01(\x03R\x05runId\"\x1d\n" +
	"\vRuleChainOk\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb5\x0e\n" +
	"\x10RuleChainService\x12j\n" +
	"\x04List\x12!.baboflow.v1.RuleChainListRequest\x1a\".baboflow.v1.RuleChainListResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/rule-chains\x12]\n" +
	"\x06Create\x12\x1b.baboflow.v1.RuleChainInput\x1a\x16.baboflow.v1.RuleChain\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/rule-chains\x12`\n" +
	"\x03Get\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a\x16.baboflow.v1.RuleChain\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/rule-chains/{id}\x12l\n" +
	"\x06Update\x12#.baboflow.v1.RuleChainUpdateRequest\x1a\x18.baboflow.v1.RuleChainOk\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/rule-chains/{id}\x12e\n" +
	"\x06Delete\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a\x18.baboflow.v1.RuleChainOk\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/rule-chains/{id}\x12\x82\x01\n" +
	"\bValidate\x12%.baboflow.v1.ValidateRuleChainRequest\x1a&.baboflow.v1.ValidateRuleChainResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/rule-chains/validate\x12~\n" +
	"\aPublish\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a%.baboflow.v1.PublishRuleChainResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/rule-chains/{id}/publish\x12q\n" +
	"\aOffline\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a\x18.baboflow.v1.RuleChainOk\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/rule-chains/{id}/offline\x12}\n" +
	"\fListVersions\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a!.baboflow.v1.RuleChainVersionList\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/rule-chains/{id}/versions\x12y\n" +
	"\bRollback\x12%.baboflow.v1.RollbackRuleChainRequest\x1a\x18.baboflow.v1.RuleChainOk\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/rule-chains/{id}/rollback\x12p\n" +
	"\x06Export\x12\x1f.baboflow.v1.RuleChainIdRequest\x1a\x1c.baboflow.v1.RuleChainExport\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/rule-chains/{id}/export\x12e\n" +
	"\x06Import\x12\x1c.baboflow.v1.RuleChainExport\x1a\x16.baboflow.v1.RuleChain\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/rule-chains/import\x12q\n" +
	"\x03Run\x12 .baboflow.v1.RunRuleChainRequest\x1a\x1f.baboflow.v1.ImmediateRunResult\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/rule-chains/{id}/run\x12u\n" +
	"\x05Debug\x12 .baboflow.v1.RunRuleChainRequest\x1a\x1f.baboflow.v1.ImmediateRunResult\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/rule-chains/{id}/debug\x12x\n" +
	"\bListRuns\x12$.baboflow.v1.RuleChainRunListRequest\x1a%.baboflow.v1.RuleChainRunListResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/rule-chain-runs\x12p\n" +
	"\x06GetRun\x12\".baboflow.v1.RuleChainRunIdRequest\x1a\x19.baboflow.v1.RuleChainRun\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/rule-chain-runs/{runId}B\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_rulechain_proto_rawDescOnce sync.Once
	file_baboflow_v1_rulechain_proto_rawDescData []byte
)

func file_baboflow_v1_rulechain_proto_rawDescGZIP() []byte {
	file_baboflow_v1_rulechain_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_rulechain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_rulechain_proto_rawDesc), len(file_baboflow_v1_rulechain_proto_rawDesc)))
	})
	return file_baboflow_v1_rulechain_proto_rawDescData
}

var file_baboflow_v1_rulechain_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_baboflow_v1_rulechain_proto_goTypes = []any{
	(*RuleChain)(nil),                 // 0: baboflow.v1.RuleChain
	(*RuleChainListItem)(nil),         // 1: baboflow.v1.RuleChainListItem
	(*RuleChainInput)(nil),            // 2: baboflow.v1.RuleChainInput
	(*RuleChainIdRequest)(nil),        // 3: baboflow.v1.RuleChainIdRequest
	(*RuleChainUpdateRequest)(nil),    // 4: baboflow.v1.RuleChainUpdateRequest
	(*RuleChainListRequest)(nil),      // 5: baboflow.v1.RuleChainListRequest
	(*RuleChainListResponse)(nil),     // 6: baboflow.v1.RuleChainListResponse
	(*ValidateRuleChainRequest)(nil),  // 7: baboflow.v1.ValidateRuleChainRequest
	(*ValidateRuleChainResponse)(nil), // 8: baboflow.v1.ValidateRuleChainResponse
	(*RuleChainVersion)(nil),          // 9: baboflow.v1.RuleChainVersion
	(*RuleChainVersionList)(nil),      // 10: baboflow.v1.RuleChainVersionList
	(*RollbackRuleChainRequest)(nil),  // 11: baboflow.v1.RollbackRuleChainRequest
	(*PublishRuleChainResponse)(nil),  // 12: baboflow.v1.PublishRuleChainResponse
	(*RuleChainExport)(nil),           // 13: baboflow.v1.RuleChainExport
	(*RunRuleChainRequest)(nil),       // 14: baboflow.v1.RunRuleChainRequest
	(*ImmediateRunResult)(nil),        // 15: baboflow.v1.ImmediateRunResult
	(*RuleChainRun)(nil),              // 16: baboflow.v1.RuleChainRun
	(*NodeTrace)(nil),                 // 17: baboflow.v1.NodeTrace
	(*TraceMessage)(nil),              // 18: baboflow.v1.TraceMessage
	(*RuleChainRunListRequest)(nil),   // 19: baboflow.v1.RuleChainRunListRequest
	(*RuleChainRunListResponse)(nil),  // 20: baboflow.v1.RuleChainRunListResponse
	(*RuleChainRunIdRequest)(nil),     // 21: baboflow.v1.RuleChainRunIdRequest
	(*RuleChainOk)(nil),               // 22: baboflow.v1.RuleChainOk
	nil,                               // 23: baboflow.v1.RunRuleChainRequest.MetadataEntry
	nil,                               // 24: baboflow.v1.TraceMessage.MetadataEntry
	(*structpb.Struct)(nil),           // 25: google.protobuf.Struct
	(*PageRequest)(nil),               // 26: baboflow.v1.PageRequest
	(*PageResponse)(nil),              // 27: baboflow.v1.PageResponse
}
var file_baboflow_v1_rulechain_proto_depIdxs = []int32{
	25, // 0: baboflow.v1.RuleChain.inputSchema:type_name -> google.protobuf.Struct
	25, // 1: baboflow.v1.RuleChain.dsl:type_name -> google.protobuf.Struct
	25, // 2: baboflow.v1.RuleChainInput.inputSchema:type_name -> google.protobuf.Struct
	25, // 3: baboflow.v1.RuleChainInput.dsl:type_name -> google.protobuf.Struct
	25, // 4: baboflow.v1.RuleChainUpdateRequest.inputSchema:type_name -> google.protobuf.Struct
	25, // 5: baboflow.v1.RuleChainUpdateRequest.dsl:type_name -> google.protobuf.Struct
	26, // 6: baboflow.v1.RuleChainListRequest.page:type_name -> baboflow.v1.PageRequest
	1,  // 7: baboflow.v1.RuleChainListResponse.list:type_name -> baboflow.v1.RuleChainListItem
	27, // 8: baboflow.v1.RuleChainListResponse.page:type_name -> baboflow.v1.PageResponse
	25, // 9: baboflow.v1.ValidateRuleChainRequest.dsl:type_name -> google.protobuf.Struct
	25, // 10: baboflow.v1.RuleChainVersion.dsl:type_name -> google.protobuf.Struct
	9,  // 11: baboflow.v1.RuleChainVersionList.list:type_name -> baboflow.v1.RuleChainVersion
	25, // 12: baboflow.v1.RuleChainExport.inputSchema:type_name -> google.protobuf.Struct
	25, // 13: baboflow.v1.RuleChainExport.dsl:type_name -> google.protobuf.Struct
	23, // 14: baboflow.v1.RunRuleChainRequest.metadata:type_name -> baboflow.v1.RunRuleChainRequest.MetadataEntry
	17, // 15: baboflow.v1.ImmediateRunResult.nodeTrace:type_name -> baboflow.v1.NodeTrace
	25, // 16: baboflow.v1.RuleChainRun.input:type_name -> google.protobuf.Struct
	25, // 17: baboflow.v1.RuleChainRun.output:type_name -> google.protobuf.Struct
	17, // 18: baboflow.v1.RuleChainRun.nodeTrace:type_name -> baboflow.v1.NodeTrace
	18, // 19: baboflow.v1.NodeTrace.input:type_name -> baboflow.v1.TraceMessage
	18, // 20: baboflow.v1.NodeTrace.output:type_name -> baboflow.v1.TraceMessage
	24, // 21: baboflow.v1.TraceMessage.metadata:type_name -> baboflow.v1.TraceMessage.MetadataEntry
	26, // 22: baboflow.v1.RuleChainRunListRequest.page:type_name -> baboflow.v1.PageRequest
	16, // 23: baboflow.v1.RuleChainRunListResponse.list:type_name -> baboflow.v1.RuleChainRun
	27, // 24: baboflow.v1.RuleChainRunListResponse.page:type_name -> baboflow.v1.PageResponse
	5,  // 25: baboflow.v1.RuleChainService.List:input_type -> baboflow.v1.RuleChainListRequest
	2,  // 26: baboflow.v1.RuleChainService.Create:input_type -> baboflow.v1.RuleChainInput
	3,  // 27: baboflow.v1.RuleChainService.Get:input_type -> baboflow.v1.RuleChainIdRequest
	4,  // 28: baboflow.v1.RuleChainService.Update:input_type -> baboflow.v1.RuleChainUpdateRequest
	3,  // 29: baboflow.v1.RuleChainService.Delete:input_type -> baboflow.v1.RuleChainIdRequest
	7,  // 30: baboflow.v1.RuleChainService.Validate:input_type -> baboflow.v1.ValidateRuleChainRequest
	3,  // 31: baboflow.v1.RuleChainService.Publish:input_type -> baboflow.v1.RuleChainIdRequest
	3,  // 32: baboflow.v1.RuleChainService.Offline:input_type -> baboflow.v1.RuleChainIdRequest
	3,  // 33: baboflow.v1.RuleChainService.ListVersions:input_type -> baboflow.v1.RuleChainIdRequest
	11, // 34: baboflow.v1.RuleChainService.Rollback:input_type -> baboflow.v1.RollbackRuleChainRequest
	3,  // 35: baboflow.v1.RuleChainService.Export:input_type -> baboflow.v1.RuleChainIdRequest
	13, // 36: baboflow.v1.RuleChainService.Import:input_type -> baboflow.v1.RuleChainExport
	14, // 37: baboflow.v1.RuleChainService.Run:input_type -> baboflow.v1.RunRuleChainRequest
	14, // 38: baboflow.v1.RuleChainService.Debug:input_type -> baboflow.v1.RunRuleChainRequest
	19, // 39: baboflow.v1.RuleChainService.ListRuns:input_type -> baboflow.v1.RuleChainRunListRequest
	21, // 40: baboflow.v1.RuleChainService.GetRun:input_type -> baboflow.v1.RuleChainRunIdRequest
	6,  // 41: baboflow.v1.RuleChainService.List:output_type -> baboflow.v1.RuleChainListResponse
	0,  // 42: baboflow.v1.RuleChainService.Create:output_type -> baboflow.v1.RuleChain
	0,  // 43: baboflow.v1.RuleChainService.Get:output_type -> baboflow.v1.RuleChain
	22, // 44: baboflow.v1.RuleChainService.Update:output_type -> baboflow.v1.RuleChainOk
	22, // 45: baboflow.v1.RuleChainService.Delete:output_type -> baboflow.v1.RuleChainOk
	8,  // 46: baboflow.v1.RuleChainService.Validate:output_type -> baboflow.v1.ValidateRuleChainResponse
	12, // 47: baboflow.v1.RuleChainService.Publish:output_type -> baboflow.v1.PublishRuleChainResponse
	22, // 48: baboflow.v1.RuleChainService.Offline:output_type -> baboflow.v1.RuleChainOk
	10, // 49: baboflow.v1.RuleChainService.ListVersions:output_type -> baboflow.v1.RuleChainVersionList
	22, // 50: baboflow.v1.RuleChainService.Rollback:output_type -> baboflow.v1.RuleChainOk
	13, // 51: baboflow.v1.RuleChainService.Export:output_type -> baboflow.v1.RuleChainExport
	0,  // 52: baboflow.v1.RuleChainService.Import:output_type -> baboflow.v1.RuleChain
	15, // 53: baboflow.v1.RuleChainService.Run:output_type -> baboflow.v1.ImmediateRunResult
	15, // 54: baboflow.v1.RuleChainService.Debug:output_type -> baboflow.v1.ImmediateRunResult
	20, // 55: baboflow.v1.RuleChainService.ListRuns:output_type -> baboflow.v1.RuleChainRunListResponse
	16, // 56: baboflow.v1.RuleChainService.GetRun:output_type -> baboflow.v1.RuleChainRun
	41, // [41:57] is the sub-list for method output_type
	25, // [25:41] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_baboflow_v1_rulechain_proto_init() }
func file_baboflow_v1_rulechain_proto_init() {
	if File_baboflow_v1_rulechain_proto != nil {
		return
	}
	file_baboflow_v1_common_proto_init()
	file_baboflow_v1_rulechain_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_rulechain_proto_rawDesc), len(file_baboflow_v1_rulechain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_rulechain_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_rulechain_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_rulechain_proto_msgTypes,
	}.Build()
	File_baboflow_v1_rulechain_proto = out.File
	file_baboflow_v1_rulechain_proto_goTypes = nil
	file_baboflow_v1_rulechain_proto_depIdxs = nil
}
