// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/rulechain.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRuleChainServiceCreate = "/baboflow.v1.RuleChainService/Create"
const OperationRuleChainServiceDebug = "/baboflow.v1.RuleChainService/Debug"
const OperationRuleChainServiceDelete = "/baboflow.v1.RuleChainService/Delete"
const OperationRuleChainServiceExport = "/baboflow.v1.RuleChainService/Export"
const OperationRuleChainServiceGet = "/baboflow.v1.RuleChainService/Get"
const OperationRuleChainServiceGetRun = "/baboflow.v1.RuleChainService/GetRun"
const OperationRuleChainServiceImport = "/baboflow.v1.RuleChainService/Import"
const OperationRuleChainServiceList = "/baboflow.v1.RuleChainService/List"
const OperationRuleChainServiceListRuns = "/baboflow.v1.RuleChainService/ListRuns"
const OperationRuleChainServiceListVersions = "/baboflow.v1.RuleChainService/ListVersions"
const OperationRuleChainServiceOffline = "/baboflow.v1.RuleChainService/Offline"
const OperationRuleChainServicePublish = "/baboflow.v1.RuleChainService/Publish"
const OperationRuleChainServiceRollback = "/baboflow.v1.RuleChainService/Rollback"
const OperationRuleChainServiceRun = "/baboflow.v1.RuleChainService/Run"
const OperationRuleChainServiceUpdate = "/baboflow.v1.RuleChainService/Update"
const OperationRuleChainServiceValidate = "/baboflow.v1.RuleChainService/Validate"

type RuleChainServiceHTTPServer interface {
	// Create Old: POST /api/v1/chains.
	Create(context.Context, *RuleChainInput) (*RuleChain, error)
	// Debug Old: POST /api/v1/chains/{id}/debug.
	Debug(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error)
	// Delete Old: DELETE /api/v1/chains/{id}.
	Delete(context.Context, *RuleChainIdRequest) (*RuleChainOk, error)
	// Export Old: GET /api/v1/chains/{id}/export.
	Export(context.Context, *RuleChainIdRequest) (*RuleChainExport, error)
	// Get Old: GET /api/v1/chains/{id}.
	Get(context.Context, *RuleChainIdRequest) (*RuleChain, error)
	// GetRun Old: GET /api/v1/chains/runs/{runId}.
	GetRun(context.Context, *RuleChainRunIdRequest) (*RuleChainRun, error)
	// Import Old: POST /api/v1/chains/import.
	Import(context.Context, *RuleChainExport) (*RuleChain, error)
	// List Old: GET /api/v1/chains?status=&keyword=&page=&pageSize=.
	List(context.Context, *RuleChainListRequest) (*RuleChainListResponse, error)
	// ListRuns Old: GET /api/v1/chains/runs?chainId=&status=&page=&pageSize=.
	ListRuns(context.Context, *RuleChainRunListRequest) (*RuleChainRunListResponse, error)
	// ListVersions Old: GET /api/v1/chains/{id}/versions.
	ListVersions(context.Context, *RuleChainIdRequest) (*RuleChainVersionList, error)
	// Offline Old: POST /api/v1/chains/{id}/offline.
	Offline(context.Context, *RuleChainIdRequest) (*RuleChainOk, error)
	// Publish Old: POST /api/v1/chains/{id}/publish.
	Publish(context.Context, *RuleChainIdRequest) (*PublishRuleChainResponse, error)
	// Rollback Old: POST /api/v1/chains/{id}/rollback.
	Rollback(context.Context, *RollbackRuleChainRequest) (*RuleChainOk, error)
	// Run Old: POST /api/v1/chains/{id}/run.
	Run(context.Context, *RunRuleChainRequest) (*ImmediateRunResult, error)
	// Update Old: PUT /api/v1/chains/{id}.
	Update(context.Context, *RuleChainUpdateRequest) (*RuleChainOk, error)
	// Validate Old: POST /api/v1/chains/validate.
	Validate(context.Context, *ValidateRuleChainRequest) (*ValidateRuleChainResponse, error)
}

func RegisterRuleChainServiceHTTPServer(s *http.Server, srv RuleChainServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/rule-chains", _RuleChainService_List5_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains", _RuleChainService_Create2_HTTP_Handler(srv))
	r.GET("/api/v1/rule-chains/{id}", _RuleChainService_Get2_HTTP_Handler(srv))
	r.PUT("/api/v1/rule-chains/{id}", _RuleChainService_Update2_HTTP_Handler(srv))
	r.DELETE("/api/v1/rule-chains/{id}", _RuleChainService_Delete3_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/validate", _RuleChainService_Validate0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{id}/publish", _RuleChainService_Publish0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{id}/offline", _RuleChainService_Offline0_HTTP_Handler(srv))
	r.GET("/api/v1/rule-chains/{id}/versions", _RuleChainService_ListVersions0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{id}/rollback", _RuleChainService_Rollback0_HTTP_Handler(srv))
	r.GET("/api/v1/rule-chains/{id}/export", _RuleChainService_Export0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/import", _RuleChainService_Import0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{id}/run", _RuleChainService_Run0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{id}/debug", _RuleChainService_Debug0_HTTP_Handler(srv))
	r.GET("/api/v1/rule-chain-runs", _RuleChainService_ListRuns0_HTTP_Handler(srv))
	r.GET("/api/v1/rule-chain-runs/{runId}", _RuleChainService_GetRun0_HTTP_Handler(srv))
}

func _RuleChainService_List5_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*RuleChainListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainListResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Create2_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainInput
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*RuleChainInput))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChain)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Get2_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChain)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Update2_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*RuleChainUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainOk)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Delete3_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainOk)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Validate0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateRuleChainRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceValidate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Validate(ctx, req.(*ValidateRuleChainRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateRuleChainResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Publish0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServicePublish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Publish(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishRuleChainResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Offline0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceOffline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Offline(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainOk)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_ListVersions0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceListVersions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVersions(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainVersionList)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Rollback0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RollbackRuleChainRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceRollback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Rollback(ctx, req.(*RollbackRuleChainRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainOk)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Export0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceExport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Export(ctx, req.(*RuleChainIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainExport)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Import0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainExport
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceImport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Import(ctx, req.(*RuleChainExport))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChain)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Run0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunRuleChainRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Run(ctx, req.(*RunRuleChainRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImmediateRunResult)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_Debug0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunRuleChainRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceDebug)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Debug(ctx, req.(*RunRuleChainRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImmediateRunResult)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_ListRuns0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainRunListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceListRuns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRuns(ctx, req.(*RuleChainRunListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainRunListResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleChainService_GetRun0_HTTP_Handler(srv RuleChainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RuleChainRunIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleChainServiceGetRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRun(ctx, req.(*RuleChainRunIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RuleChainRun)
		return ctx.Result(200, reply)
	}
}

type RuleChainServiceHTTPClient interface {
	// Create Old: POST /api/v1/chains.
	Create(ctx context.Context, req *RuleChainInput, opts ...http.CallOption) (rsp *RuleChain, err error)
	// Debug Old: POST /api/v1/chains/{id}/debug.
	Debug(ctx context.Context, req *RunRuleChainRequest, opts ...http.CallOption) (rsp *ImmediateRunResult, err error)
	// Delete Old: DELETE /api/v1/chains/{id}.
	Delete(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *RuleChainOk, err error)
	// Export Old: GET /api/v1/chains/{id}/export.
	Export(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *RuleChainExport, err error)
	// Get Old: GET /api/v1/chains/{id}.
	Get(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *RuleChain, err error)
	// GetRun Old: GET /api/v1/chains/runs/{runId}.
	GetRun(ctx context.Context, req *RuleChainRunIdRequest, opts ...http.CallOption) (rsp *RuleChainRun, err error)
	// Import Old: POST /api/v1/chains/import.
	Import(ctx context.Context, req *RuleChainExport, opts ...http.CallOption) (rsp *RuleChain, err error)
	// List Old: GET /api/v1/chains?status=&keyword=&page=&pageSize=.
	List(ctx context.Context, req *RuleChainListRequest, opts ...http.CallOption) (rsp *RuleChainListResponse, err error)
	// ListRuns Old: GET /api/v1/chains/runs?chainId=&status=&page=&pageSize=.
	ListRuns(ctx context.Context, req *RuleChainRunListRequest, opts ...http.CallOption) (rsp *RuleChainRunListResponse, err error)
	// ListVersions Old: GET /api/v1/chains/{id}/versions.
	ListVersions(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *RuleChainVersionList, err error)
	// Offline Old: POST /api/v1/chains/{id}/offline.
	Offline(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *RuleChainOk, err error)
	// Publish Old: POST /api/v1/chains/{id}/publish.
	Publish(ctx context.Context, req *RuleChainIdRequest, opts ...http.CallOption) (rsp *PublishRuleChainResponse, err error)
	// Rollback Old: POST /api/v1/chains/{id}/rollback.
	Rollback(ctx context.Context, req *RollbackRuleChainRequest, opts ...http.CallOption) (rsp *RuleChainOk, err error)
	// Run Old: POST /api/v1/chains/{id}/run.
	Run(ctx context.Context, req *RunRuleChainRequest, opts ...http.CallOption) (rsp *ImmediateRunResult, err error)
	// Update Old: PUT /api/v1/chains/{id}.
	Update(ctx context.Context, req *RuleChainUpdateRequest, opts ...http.CallOption) (rsp *RuleChainOk, err error)
	// Validate Old: POST /api/v1/chains/validate.
	Validate(ctx context.Context, req *ValidateRuleChainRequest, opts ...http.CallOption) (rsp *ValidateRuleChainResponse, err error)
}

type RuleChainServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRuleChainServiceHTTPClient(client *http.Client) RuleChainServiceHTTPClient {
	return &RuleChainServiceHTTPClientImpl{client}
}

// Create Old: POST /api/v1/chains.
func (c *RuleChainServiceHTTPClientImpl) Create(ctx context.Context, in *RuleChainInput, opts ...http.CallOption) (*RuleChain, error) {
	var out RuleChain
	pattern := "/api/v1/rule-chains"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Debug Old: POST /api/v1/chains/{id}/debug.
func (c *RuleChainServiceHTTPClientImpl) Debug(ctx context.Context, in *RunRuleChainRequest, opts ...http.CallOption) (*ImmediateRunResult, error) {
	var out ImmediateRunResult
	pattern := "/api/v1/rule-chains/{id}/debug"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceDebug))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete Old: DELETE /api/v1/chains/{id}.
func (c *RuleChainServiceHTTPClientImpl) Delete(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*RuleChainOk, error) {
	var out RuleChainOk
	pattern := "/api/v1/rule-chains/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Export Old: GET /api/v1/chains/{id}/export.
func (c *RuleChainServiceHTTPClientImpl) Export(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*RuleChainExport, error) {
	var out RuleChainExport
	pattern := "/api/v1/rule-chains/{id}/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceExport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Old: GET /api/v1/chains/{id}.
func (c *RuleChainServiceHTTPClientImpl) Get(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*RuleChain, error) {
	var out RuleChain
	pattern := "/api/v1/rule-chains/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRun Old: GET /api/v1/chains/runs/{runId}.
func (c *RuleChainServiceHTTPClientImpl) GetRun(ctx context.Context, in *RuleChainRunIdRequest, opts ...http.CallOption) (*RuleChainRun, error) {
	var out RuleChainRun
	pattern := "/api/v1/rule-chain-runs/{runId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceGetRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Import Old: POST /api/v1/chains/import.
func (c *RuleChainServiceHTTPClientImpl) Import(ctx context.Context, in *RuleChainExport, opts ...http.CallOption) (*RuleChain, error) {
	var out RuleChain
	pattern := "/api/v1/rule-chains/import"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceImport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List Old: GET /api/v1/chains?status=&keyword=&page=&pageSize=.
func (c *RuleChainServiceHTTPClientImpl) List(ctx context.Context, in *RuleChainListRequest, opts ...http.CallOption) (*RuleChainListResponse, error) {
	var out RuleChainListResponse
	pattern := "/api/v1/rule-chains"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRuns Old: GET /api/v1/chains/runs?chainId=&status=&page=&pageSize=.
func (c *RuleChainServiceHTTPClientImpl) ListRuns(ctx context.Context, in *RuleChainRunListRequest, opts ...http.CallOption) (*RuleChainRunListResponse, error) {
	var out RuleChainRunListResponse
	pattern := "/api/v1/rule-chain-runs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceListRuns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListVersions Old: GET /api/v1/chains/{id}/versions.
func (c *RuleChainServiceHTTPClientImpl) ListVersions(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*RuleChainVersionList, error) {
	var out RuleChainVersionList
	pattern := "/api/v1/rule-chains/{id}/versions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleChainServiceListVersions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Offline Old: POST /api/v1/chains/{id}/offline.
func (c *RuleChainServiceHTTPClientImpl) Offline(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*RuleChainOk, error) {
	var out RuleChainOk
	pattern := "/api/v1/rule-chains/{id}/offline"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceOffline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Publish Old: POST /api/v1/chains/{id}/publish.
func (c *RuleChainServiceHTTPClientImpl) Publish(ctx context.Context, in *RuleChainIdRequest, opts ...http.CallOption) (*PublishRuleChainResponse, error) {
	var out PublishRuleChainResponse
	pattern := "/api/v1/rule-chains/{id}/publish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServicePublish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Rollback Old: POST /api/v1/chains/{id}/rollback.
func (c *RuleChainServiceHTTPClientImpl) Rollback(ctx context.Context, in *RollbackRuleChainRequest, opts ...http.CallOption) (*RuleChainOk, error) {
	var out RuleChainOk
	pattern := "/api/v1/rule-chains/{id}/rollback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceRollback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Run Old: POST /api/v1/chains/{id}/run.
func (c *RuleChainServiceHTTPClientImpl) Run(ctx context.Context, in *RunRuleChainRequest, opts ...http.CallOption) (*ImmediateRunResult, error) {
	var out ImmediateRunResult
	pattern := "/api/v1/rule-chains/{id}/run"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update Old: PUT /api/v1/chains/{id}.
func (c *RuleChainServiceHTTPClientImpl) Update(ctx context.Context, in *RuleChainUpdateRequest, opts ...http.CallOption) (*RuleChainOk, error) {
	var out RuleChainOk
	pattern := "/api/v1/rule-chains/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Validate Old: POST /api/v1/chains/validate.
func (c *RuleChainServiceHTTPClientImpl) Validate(ctx context.Context, in *ValidateRuleChainRequest, opts ...http.CallOption) (*ValidateRuleChainResponse, error) {
	var out ValidateRuleChainResponse
	pattern := "/api/v1/rule-chains/validate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleChainServiceValidate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
