// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: baboflow/v1/skill.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillService_List_FullMethodName      = "/baboflow.v1.SkillService/List"
	SkillService_Upload_FullMethodName    = "/baboflow.v1.SkillService/Upload"
	SkillService_Get_FullMethodName       = "/baboflow.v1.SkillService/Get"
	SkillService_Delete_FullMethodName    = "/baboflow.v1.SkillService/Delete"
	SkillService_ListFiles_FullMethodName = "/baboflow.v1.SkillService/ListFiles"
	SkillService_ReadFile_FullMethodName  = "/baboflow.v1.SkillService/ReadFile"
	SkillService_Generate_FullMethodName  = "/baboflow.v1.SkillService/Generate"
)

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillServiceClient interface {
	// Old: GET /api/v1/skills?source=&keyword=.
	List(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error)
	// Old: POST /api/v1/skills.
	Upload(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	// Old: GET /api/v1/skills/{id}.
	Get(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*Skill, error)
	// Old: DELETE /api/v1/skills/{id}.
	Delete(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*SkillOk, error)
	// Old: GET /api/v1/skills/{id}/files.
	ListFiles(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*SkillFileList, error)
	// Old: GET /api/v1/skills/{id}/file?path=.
	ReadFile(ctx context.Context, in *ReadSkillFileRequest, opts ...grpc.CallOption) (*ReadSkillFileResponse, error)
	// Old: POST /api/v1/chains/{id}/skill.
	Generate(ctx context.Context, in *GenerateSkillRequest, opts ...grpc.CallOption) (*Skill, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) List(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillListResponse)
	err := c.cc.Invoke(ctx, SkillService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) Upload(ctx context.Context, in *UploadSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) Get(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) Delete(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*SkillOk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillOk)
	err := c.cc.Invoke(ctx, SkillService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ListFiles(ctx context.Context, in *SkillIdRequest, opts ...grpc.CallOption) (*SkillFileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillFileList)
	err := c.cc.Invoke(ctx, SkillService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) ReadFile(ctx context.Context, in *ReadSkillFileRequest, opts ...grpc.CallOption) (*ReadSkillFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSkillFileResponse)
	err := c.cc.Invoke(ctx, SkillService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) Generate(ctx context.Context, in *GenerateSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
// All implementations must embed UnimplementedSkillServiceServer
// for forward compatibility.
type SkillServiceServer interface {
	// Old: GET /api/v1/skills?source=&keyword=.
	List(context.Context, *SkillListRequest) (*SkillListResponse, error)
	// Old: POST /api/v1/skills.
	Upload(context.Context, *UploadSkillRequest) (*Skill, error)
	// Old: GET /api/v1/skills/{id}.
	Get(context.Context, *SkillIdRequest) (*Skill, error)
	// Old: DELETE /api/v1/skills/{id}.
	Delete(context.Context, *SkillIdRequest) (*SkillOk, error)
	// Old: GET /api/v1/skills/{id}/files.
	ListFiles(context.Context, *SkillIdRequest) (*SkillFileList, error)
	// Old: GET /api/v1/skills/{id}/file?path=.
	ReadFile(context.Context, *ReadSkillFileRequest) (*ReadSkillFileResponse, error)
	// Old: POST /api/v1/chains/{id}/skill.
	Generate(context.Context, *GenerateSkillRequest) (*Skill, error)
	mustEmbedUnimplementedSkillServiceServer()
}

// UnimplementedSkillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillServiceServer struct{}

func (UnimplementedSkillServiceServer) List(context.Context, *SkillListRequest) (*SkillListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSkillServiceServer) Upload(context.Context, *UploadSkillRequest) (*Skill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedSkillServiceServer) Get(context.Context, *SkillIdRequest) (*Skill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSkillServiceServer) Delete(context.Context, *SkillIdRequest) (*SkillOk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSkillServiceServer) ListFiles(context.Context, *SkillIdRequest) (*SkillFileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedSkillServiceServer) ReadFile(context.Context, *ReadSkillFileRequest) (*ReadSkillFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSkillServiceServer) Generate(context.Context, *GenerateSkillRequest) (*Skill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedSkillServiceServer) mustEmbedUnimplementedSkillServiceServer() {}
func (UnimplementedSkillServiceServer) testEmbeddedByValue()                      {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).List(ctx, req.(*SkillListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Upload(ctx, req.(*UploadSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Get(ctx, req.(*SkillIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Delete(ctx, req.(*SkillIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ListFiles(ctx, req.(*SkillIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSkillFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).ReadFile(ctx, req.(*ReadSkillFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Generate(ctx, req.(*GenerateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "baboflow.v1.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SkillService_List_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _SkillService_Upload_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SkillService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SkillService_Delete_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _SkillService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SkillService_ReadFile_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _SkillService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baboflow/v1/skill.proto",
}
