// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: baboflow/v1/skill.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSkillServiceDelete = "/baboflow.v1.SkillService/Delete"
const OperationSkillServiceGenerate = "/baboflow.v1.SkillService/Generate"
const OperationSkillServiceGet = "/baboflow.v1.SkillService/Get"
const OperationSkillServiceList = "/baboflow.v1.SkillService/List"
const OperationSkillServiceListFiles = "/baboflow.v1.SkillService/ListFiles"
const OperationSkillServiceReadFile = "/baboflow.v1.SkillService/ReadFile"
const OperationSkillServiceUpload = "/baboflow.v1.SkillService/Upload"

type SkillServiceHTTPServer interface {
	// Delete Old: DELETE /api/v1/skills/{id}.
	Delete(context.Context, *SkillIdRequest) (*SkillOk, error)
	// Generate Old: POST /api/v1/chains/{id}/skill.
	Generate(context.Context, *GenerateSkillRequest) (*Skill, error)
	// Get Old: GET /api/v1/skills/{id}.
	Get(context.Context, *SkillIdRequest) (*Skill, error)
	// List Old: GET /api/v1/skills?source=&keyword=.
	List(context.Context, *SkillListRequest) (*SkillListResponse, error)
	// ListFiles Old: GET /api/v1/skills/{id}/files.
	ListFiles(context.Context, *SkillIdRequest) (*SkillFileList, error)
	// ReadFile Old: GET /api/v1/skills/{id}/file?path=.
	ReadFile(context.Context, *ReadSkillFileRequest) (*ReadSkillFileResponse, error)
	// Upload Old: POST /api/v1/skills.
	Upload(context.Context, *UploadSkillRequest) (*Skill, error)
}

func RegisterSkillServiceHTTPServer(s *http.Server, srv SkillServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/skills", _SkillService_List2_HTTP_Handler(srv))
	r.POST("/api/v1/skills", _SkillService_Upload0_HTTP_Handler(srv))
	r.GET("/api/v1/skills/{id}", _SkillService_Get0_HTTP_Handler(srv))
	r.DELETE("/api/v1/skills/{id}", _SkillService_Delete0_HTTP_Handler(srv))
	r.GET("/api/v1/skills/{id}/files", _SkillService_ListFiles0_HTTP_Handler(srv))
	r.GET("/api/v1/skills/{id}/file", _SkillService_ReadFile0_HTTP_Handler(srv))
	r.POST("/api/v1/rule-chains/{chainId}/skill", _SkillService_Generate0_HTTP_Handler(srv))
}

func _SkillService_List2_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*SkillListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillListResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_Upload0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Upload(ctx, req.(*UploadSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_Get0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*SkillIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

func _SkillService_Delete0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*SkillIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillOk)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ListFiles0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SkillIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceListFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFiles(ctx, req.(*SkillIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SkillFileList)
		return ctx.Result(200, reply)
	}
}

func _SkillService_ReadFile0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReadSkillFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceReadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReadFile(ctx, req.(*ReadSkillFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReadSkillFileResponse)
		return ctx.Result(200, reply)
	}
}

func _SkillService_Generate0_HTTP_Handler(srv SkillServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateSkillRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSkillServiceGenerate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Generate(ctx, req.(*GenerateSkillRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Skill)
		return ctx.Result(200, reply)
	}
}

type SkillServiceHTTPClient interface {
	// Delete Old: DELETE /api/v1/skills/{id}.
	Delete(ctx context.Context, req *SkillIdRequest, opts ...http.CallOption) (rsp *SkillOk, err error)
	// Generate Old: POST /api/v1/chains/{id}/skill.
	Generate(ctx context.Context, req *GenerateSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// Get Old: GET /api/v1/skills/{id}.
	Get(ctx context.Context, req *SkillIdRequest, opts ...http.CallOption) (rsp *Skill, err error)
	// List Old: GET /api/v1/skills?source=&keyword=.
	List(ctx context.Context, req *SkillListRequest, opts ...http.CallOption) (rsp *SkillListResponse, err error)
	// ListFiles Old: GET /api/v1/skills/{id}/files.
	ListFiles(ctx context.Context, req *SkillIdRequest, opts ...http.CallOption) (rsp *SkillFileList, err error)
	// ReadFile Old: GET /api/v1/skills/{id}/file?path=.
	ReadFile(ctx context.Context, req *ReadSkillFileRequest, opts ...http.CallOption) (rsp *ReadSkillFileResponse, err error)
	// Upload Old: POST /api/v1/skills.
	Upload(ctx context.Context, req *UploadSkillRequest, opts ...http.CallOption) (rsp *Skill, err error)
}

type SkillServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSkillServiceHTTPClient(client *http.Client) SkillServiceHTTPClient {
	return &SkillServiceHTTPClientImpl{client}
}

// Delete Old: DELETE /api/v1/skills/{id}.
func (c *SkillServiceHTTPClientImpl) Delete(ctx context.Context, in *SkillIdRequest, opts ...http.CallOption) (*SkillOk, error) {
	var out SkillOk
	pattern := "/api/v1/skills/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSkillServiceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Generate Old: POST /api/v1/chains/{id}/skill.
func (c *SkillServiceHTTPClientImpl) Generate(ctx context.Context, in *GenerateSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/api/v1/rule-chains/{chainId}/skill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSkillServiceGenerate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get Old: GET /api/v1/skills/{id}.
func (c *SkillServiceHTTPClientImpl) Get(ctx context.Context, in *SkillIdRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/api/v1/skills/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSkillServiceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List Old: GET /api/v1/skills?source=&keyword=.
func (c *SkillServiceHTTPClientImpl) List(ctx context.Context, in *SkillListRequest, opts ...http.CallOption) (*SkillListResponse, error) {
	var out SkillListResponse
	pattern := "/api/v1/skills"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSkillServiceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListFiles Old: GET /api/v1/skills/{id}/files.
func (c *SkillServiceHTTPClientImpl) ListFiles(ctx context.Context, in *SkillIdRequest, opts ...http.CallOption) (*SkillFileList, error) {
	var out SkillFileList
	pattern := "/api/v1/skills/{id}/files"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSkillServiceListFiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReadFile Old: GET /api/v1/skills/{id}/file?path=.
func (c *SkillServiceHTTPClientImpl) ReadFile(ctx context.Context, in *ReadSkillFileRequest, opts ...http.CallOption) (*ReadSkillFileResponse, error) {
	var out ReadSkillFileResponse
	pattern := "/api/v1/skills/{id}/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSkillServiceReadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Upload Old: POST /api/v1/skills.
func (c *SkillServiceHTTPClientImpl) Upload(ctx context.Context, in *UploadSkillRequest, opts ...http.CallOption) (*Skill, error) {
	var out Skill
	pattern := "/api/v1/skills"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSkillServiceUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
