// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: baboflow/v1/skill.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ChainId       string                 `protobuf:"bytes,5,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Frontmatter   *structpb.Struct       `protobuf:"bytes,6,opt,name=frontmatter,proto3" json:"frontmatter,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	HasFiles      bool                   `protobuf:"varint,8,opt,name=hasFiles,proto3" json:"hasFiles,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Skill) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Skill) GetFrontmatter() *structpb.Struct {
	if x != nil {
		return x.Frontmatter
	}
	return nil
}

func (x *Skill) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Skill) GetHasFiles() bool {
	if x != nil {
		return x.HasFiles
	}
	return false
}

func (x *Skill) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SkillListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListRequest) Reset() {
	*x = SkillListRequest{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListRequest) ProtoMessage() {}

func (x *SkillListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListRequest.ProtoReflect.Descriptor instead.
func (*SkillListRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillListRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SkillListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SkillListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Skill               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListResponse) Reset() {
	*x = SkillListResponse{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListResponse) ProtoMessage() {}

func (x *SkillListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListResponse.ProtoReflect.Descriptor instead.
func (*SkillListResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{2}
}

func (x *SkillListResponse) GetList() []*Skill {
	if x != nil {
		return x.List
	}
	return nil
}

type SkillIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillIdRequest) Reset() {
	*x = SkillIdRequest{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillIdRequest) ProtoMessage() {}

func (x *SkillIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillIdRequest.ProtoReflect.Descriptor instead.
func (*SkillIdRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{3}
}

func (x *SkillIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UploadSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSkillRequest) Reset() {
	*x = UploadSkillRequest{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSkillRequest) ProtoMessage() {}

func (x *UploadSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSkillRequest.ProtoReflect.Descriptor instead.
func (*UploadSkillRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{4}
}

func (x *UploadSkillRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UploadSkillRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SkillFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=isDir,proto3" json:"isDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillFile) Reset() {
	*x = SkillFile{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillFile) ProtoMessage() {}

func (x *SkillFile) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillFile.ProtoReflect.Descriptor instead.
func (*SkillFile) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{5}
}

func (x *SkillFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SkillFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SkillFile) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type SkillFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SkillFile           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillFileList) Reset() {
	*x = SkillFileList{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillFileList) ProtoMessage() {}

func (x *SkillFileList) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillFileList.ProtoReflect.Descriptor instead.
func (*SkillFileList) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{6}
}

func (x *SkillFileList) GetList() []*SkillFile {
	if x != nil {
		return x.List
	}
	return nil
}

type ReadSkillFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSkillFileRequest) Reset() {
	*x = ReadSkillFileRequest{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSkillFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSkillFileRequest) ProtoMessage() {}

func (x *ReadSkillFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSkillFileRequest.ProtoReflect.Descriptor instead.
func (*ReadSkillFileRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{7}
}

func (x *ReadSkillFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadSkillFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadSkillFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSkillFileResponse) Reset() {
	*x = ReadSkillFileResponse{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSkillFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSkillFileResponse) ProtoMessage() {}

func (x *ReadSkillFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSkillFileResponse.ProtoReflect.Descriptor instead.
func (*ReadSkillFileResponse) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{8}
}

func (x *ReadSkillFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadSkillFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSkillRequest) Reset() {
	*x = GenerateSkillRequest{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSkillRequest) ProtoMessage() {}

func (x *GenerateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSkillRequest.ProtoReflect.Descriptor instead.
func (*GenerateSkillRequest) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateSkillRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type SkillOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillOk) Reset() {
	*x = SkillOk{}
	mi := &file_baboflow_v1_skill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillOk) ProtoMessage() {}

func (x *SkillOk) ProtoReflect() protoreflect.Message {
	mi := &file_baboflow_v1_skill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillOk.ProtoReflect.Descriptor instead.
func (*SkillOk) Descriptor() ([]byte, []int) {
	return file_baboflow_v1_skill_proto_rawDescGZIP(), []int{10}
}

func (x *SkillOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_baboflow_v1_skill_proto protoreflect.FileDescriptor

const file_baboflow_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x17baboflow/v1/skill.proto\x12\vbaboflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x02\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\achainId\x18\x05 \x01(\tR\achainId\x129\n" +
	"\vfrontmatter\x18\x06 \x01(\v2\x17.google.protobuf.StructR\vfrontmatter\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1a\n" +
	"\bhasFiles\x18\b \x01(\bR\bhasFiles\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\"D\n" +
	"\x10SkillListRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\";\n" +
	"\x11SkillListResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.baboflow.v1.SkillR\x04list\" \n" +
	"\x0eSkillIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x12UploadSkillRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"I\n" +
	"\tSkillFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05isDir\x18\x03 \x01(\bR\x05isDir\";\n" +
	"\rSkillFileList\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.baboflow.v1.SkillFileR\x04list\":\n" +
	"\x14ReadSkillFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"E\n" +
	"\x15ReadSkillFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"0\n" +
	"\x14GenerateSkillRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\"\x19\n" +
	"\aSkillOk\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xc7\x05\n" +
	"\fSkillService\x12]\n" +
	"\x04List\x12\x1d.baboflow.v1.SkillListRequest\x1a\x1e.baboflow.v1.SkillListResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/skills\x12X\n" +
	"\x06Upload\x12\x1f.baboflow.v1.UploadSkillRequest\x1a\x12.baboflow.v1.Skill\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/skills\x12S\n" +
	"\x03Get\x12\x1b.baboflow.v1.SkillIdRequest\x1a\x12.baboflow.v1.Skill\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/skills/{id}\x12X\n" +
	"\x06Delete\x12\x1b.baboflow.v1.SkillIdRequest\x1a\x14.baboflow.v1.SkillOk\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/skills/{id}\x12g\n" +
	"\tListFiles\x12\x1b.baboflow.v1.SkillIdRequest\x1a\x1a.baboflow.v1.SkillFileList\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/skills/{id}/files\x12s\n" +
	"\bReadFile\x12!.baboflow.v1.ReadSkillFileRequest\x1a\".baboflow.v1.ReadSkillFileResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/skills/{id}/file\x12q\n" +
	"\bGenerate\x12!.baboflow.v1.GenerateSkillRequest\x1a\x12.baboflow.v1.Skill\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/rule-chains/{chainId}/skillB\x1dZ\x1bbaboflow/api/baboflow/v1;v1b\x06proto3"

var (
	file_baboflow_v1_skill_proto_rawDescOnce sync.Once
	file_baboflow_v1_skill_proto_rawDescData []byte
)

func file_baboflow_v1_skill_proto_rawDescGZIP() []byte {
	file_baboflow_v1_skill_proto_rawDescOnce.Do(func() {
		file_baboflow_v1_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baboflow_v1_skill_proto_rawDesc), len(file_baboflow_v1_skill_proto_rawDesc)))
	})
	return file_baboflow_v1_skill_proto_rawDescData
}

var file_baboflow_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_baboflow_v1_skill_proto_goTypes = []any{
	(*Skill)(nil),                 // 0: baboflow.v1.Skill
	(*SkillListRequest)(nil),      // 1: baboflow.v1.SkillListRequest
	(*SkillListResponse)(nil),     // 2: baboflow.v1.SkillListResponse
	(*SkillIdRequest)(nil),        // 3: baboflow.v1.SkillIdRequest
	(*UploadSkillRequest)(nil),    // 4: baboflow.v1.UploadSkillRequest
	(*SkillFile)(nil),             // 5: baboflow.v1.SkillFile
	(*SkillFileList)(nil),         // 6: baboflow.v1.SkillFileList
	(*ReadSkillFileRequest)(nil),  // 7: baboflow.v1.ReadSkillFileRequest
	(*ReadSkillFileResponse)(nil), // 8: baboflow.v1.ReadSkillFileResponse
	(*GenerateSkillRequest)(nil),  // 9: baboflow.v1.GenerateSkillRequest
	(*SkillOk)(nil),               // 10: baboflow.v1.SkillOk
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
}
var file_baboflow_v1_skill_proto_depIdxs = []int32{
	11, // 0: baboflow.v1.Skill.frontmatter:type_name -> google.protobuf.Struct
	0,  // 1: baboflow.v1.SkillListResponse.list:type_name -> baboflow.v1.Skill
	5,  // 2: baboflow.v1.SkillFileList.list:type_name -> baboflow.v1.SkillFile
	1,  // 3: baboflow.v1.SkillService.List:input_type -> baboflow.v1.SkillListRequest
	4,  // 4: baboflow.v1.SkillService.Upload:input_type -> baboflow.v1.UploadSkillRequest
	3,  // 5: baboflow.v1.SkillService.Get:input_type -> baboflow.v1.SkillIdRequest
	3,  // 6: baboflow.v1.SkillService.Delete:input_type -> baboflow.v1.SkillIdRequest
	3,  // 7: baboflow.v1.SkillService.ListFiles:input_type -> baboflow.v1.SkillIdRequest
	7,  // 8: baboflow.v1.SkillService.ReadFile:input_type -> baboflow.v1.ReadSkillFileRequest
	9,  // 9: baboflow.v1.SkillService.Generate:input_type -> baboflow.v1.GenerateSkillRequest
	2,  // 10: baboflow.v1.SkillService.List:output_type -> baboflow.v1.SkillListResponse
	0,  // 11: baboflow.v1.SkillService.Upload:output_type -> baboflow.v1.Skill
	0,  // 12: baboflow.v1.SkillService.Get:output_type -> baboflow.v1.Skill
	10, // 13: baboflow.v1.SkillService.Delete:output_type -> baboflow.v1.SkillOk
	6,  // 14: baboflow.v1.SkillService.ListFiles:output_type -> baboflow.v1.SkillFileList
	8,  // 15: baboflow.v1.SkillService.ReadFile:output_type -> baboflow.v1.ReadSkillFileResponse
	0,  // 16: baboflow.v1.SkillService.Generate:output_type -> baboflow.v1.Skill
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_baboflow_v1_skill_proto_init() }
func file_baboflow_v1_skill_proto_init() {
	if File_baboflow_v1_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baboflow_v1_skill_proto_rawDesc), len(file_baboflow_v1_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baboflow_v1_skill_proto_goTypes,
		DependencyIndexes: file_baboflow_v1_skill_proto_depIdxs,
		MessageInfos:      file_baboflow_v1_skill_proto_msgTypes,
	}.Build()
	File_baboflow_v1_skill_proto = out.File
	file_baboflow_v1_skill_proto_goTypes = nil
	file_baboflow_v1_skill_proto_depIdxs = nil
}
